/* Tempest Walker campaign definitions and deterministic simulation. No rendering dependency. */
(function(root){'use strict';
 const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z),copy=o=>JSON.parse(JSON.stringify(o));
 const elements=[{name:'Air',glyph:'風',color:'#bde5c9'},{name:'Fire',glyph:'火',color:'#ffac58'},{name:'Lightning',glyph:'雷',color:'#bf71ff'},{name:'Water',glyph:'水',color:'#83dbe5'},{name:'Earth',glyph:'土',color:'#e4c180'}];
 const damageScale=[1,1.2,1.45,1.75,2.1,2.5,3];
 const tierFeatures=['Awakening','Secondary strikes','Persistent fields','Crowd control','Amplified reactions','Repeated impacts','Mastery forms'];
 const powerNames=[
 ['Gale blade','Twin gust','Pressure field','Vortex','Scorchwind','Convergence','Cyclone'],
 ['Flame stream','Forked flame','Burning ground','Blazing front','Elemental ignition','Eruption','Phoenix firestorm'],
 ['Hand bolt','Chain bolt','Storm field','Thunderclap','Conductive storm','Repeated judgments','Judgment column'],
 ['Great wave','Twin surge','Undertow','Tidal vortex','Steam tide','Breaker cascade','Ocean procession'],
 ['Stone eruption','Fracture','Stone field','Faultline','Molten fracture','Aftershock','Worldbreaker']];

 class LevelDefinition{constructor(id,name,theme,boss,music,combat,puzzles,story){
  Object.assign(this,{id,name,theme,boss,music,combat:combat||music,story,length:590,targetSeconds:120,
   puzzles:puzzles.map(([z,element,label])=>[z*.5,element,label]),encounters:[120,290,480],waves:1,waveSize:[5,6,6,7,7,8,8][id],
   checkpoints:[8,65,195,320,420,515],discoveryZ:[18,80,205,330,425],shrine:{x:34,z:355},bossZ:560,bossTrigger:530,landmark:550,
   ramps:[{start:215,length:30,height:2,rise:10},{start:365,length:30,height:2,rise:10}],blizzard:{start:375,end:395}});
  this.routes=[0,90,170,260,350,440,520,590].map((z,i)=>({x:i===0?0:Math.sin(i*1.9+id*.8)*(id===1?13:9),z}));
  this.areas=this.encounters.map(z=>({x:this.centerAt(z),z,width:40,depth:80}));this.shrine.x+=this.centerAt(this.shrine.z);
 }
 centerAt(z){const r=this.routes;if(!r)return 0;for(let i=1;i<r.length;i++)if(z<=r[i].z){const a=r[i-1],b=r[i],t=clamp((z-a.z)/(b.z-a.z),0,1),u=t*t*(3-2*t);return a.x+(b.x-a.x)*u;}return r[r.length-1].x;} }
 const levels=[
 new LevelDefinition(0,'The Ashen City','japan','Bell Warden','asian-drums.mp3',null,[[90,1,'Burn the barricaded market'],[350,0,'Disperse the incense veil'],[530,2,'Restore the canal mechanism'],[790,3,'Quench the burning district'],[910,4,'Raise the shattered causeway']],'Five sleeping elements wait within the city. Follow the fractures through its five districts.'),
 new LevelDefinition(1,'Dust and Iron','west','Iron Marshal','western.mp3',null,[[350,0,'Clear the canyon dust'],[800,1,'Break the rail-yard barricade']],'The fracture opens onto a frontier under siege. Break the Marshal’s blockade and follow the railway.'),
 new LevelDefinition(2,'Neon Underworld','cyber','Grid Executor','neon.mp3','ai-fight.mp3',[[350,2,'Redirect the district power'],[800,3,'Cool the reactor conduits']],'A corporate intelligence is harvesting the fracture. Reach its power station and sever the relay network.'),
 new LevelDefinition(3,'Tomb of the Sun','egypt','Sun Colossus','scarab.mp3',null,[[350,0,'Uncover the buried gate'],[800,3,'Fill the ancient water channel']],'Beneath the dunes, a buried guardian wakes. Restore the channels and enter the sun court.'),
 new LevelDefinition(4,'The Frostbound Citadel','ice','Rime Jarl','long-dark.mp3','legionnaire.mp3',[[350,1,'Melt the frozen fortress gate'],[800,4,'Raise shelter across the icefield']],'A winter without end holds the citadel. Shelter from the gale and break the Jarl’s hold on the fracture.'),
 new LevelDefinition(5,'Cathedral of Cinders','gothic','Bell Engine','old-ones.ogg',null,[[350,0,'Vent the poisoned foundry'],[800,3,'Extinguish the cathedral approach']],'The bells are machines, and the city is their furnace. Silence the engine beneath the cathedral.'),
 new LevelDefinition(6,'The Shattered Metropolis','celestial','Rift Sovereign','ascension.mp3',null,[[350,4,'Rebuild the suspended causeway'],[800,2,'Awaken the celestial bridge']],'An Art Deco metropolis rises beneath the fractured sky. Cross its elevated railways and confront the Sovereign at Meridian Tower.')];
 const showcaseLevel=new LevelDefinition(0,'Ashen City · Storm Awakening','japan','Bell Warden','asian-drums.mp3','japan-battle.mp3',[],'Follow the storm through the rain garden.');Object.assign(showcaseLevel,{length:250,encounters:[40,110,175],checkpoints:[8,65,140,195,205,210],discoveryZ:[],shrine:{x:30,z:240},bossZ:225,bossTrigger:200,landmark:240,ramps:[{start:145,length:25,height:1.4,rise:8}],waveSize:5,routes:[{x:0,z:0},{x:0,z:70},{x:5,z:130},{x:0,z:190},{x:0,z:250}]});
 const SAVE_KEY='fivefold-seven-worlds-v1';
 class CampaignState{
  constructor(){this.version=2;this.level=0;this.highest=0;this.completed=[];this.unlocked=[];this.specializations=Array.from({length:5},()=>({impact:0,control:0}));this.mastery=[];this.snapshot=null;this.time=0;this.deaths=0;}
  get earned(){return this.completed.filter(i=>i<6).length*5;}get spent(){return this.specializations.reduce((n,s)=>n+s.impact+s.control,0);}get points(){return this.earned-this.spent;}
  upgrade(el,branch){if(!Number.isInteger(el)||el<0||el>4||!['impact','control'].includes(branch)||this.points<=0||this.specializations[el][branch]>=3)return false;this.specializations[el][branch]++;return true;}
  upgradeAll(){let assigned=0;while(this.points>0){const choices=this.specializations.flatMap((s,el)=>["impact","control"].filter(branch=>s[branch]<3).map(branch=>({el,branch,rank:s[branch],total:s.impact+s.control}))).sort((a,b)=>a.total-b.total||a.rank-b.rank||a.el-b.el);if(!choices.length)break;const {el,branch}=choices[0];if(!this.upgrade(el,branch))break;assigned++;}return assigned;}
  refund(){this.specializations.forEach(s=>{s.impact=s.control=0;});}
  serialize(){return JSON.stringify(this);}
  static parse(text){if(typeof text!=='string'||text.length>500000)throw Error('Invalid save file.');const v=JSON.parse(text);if(![1,2].includes(v.version))throw Error('Unsupported save version.');const integers=(a,max)=>Array.isArray(a)&&a.length<=max+1&&a.every(n=>Number.isInteger(n)&&n>=0&&n<=max)&&new Set(a).size===a.length;if(!integers(v.completed,6)||!integers(v.unlocked,4)||!Number.isInteger(v.level)||v.level<0||v.level>6||!Number.isInteger(v.highest)||v.highest<0||v.highest>6)throw Error('Invalid campaign progress.');if(v.completed.some(i=>i>v.highest)||v.level>v.highest)throw Error('Inconsistent campaign progress.');if(!Array.isArray(v.specializations)||v.specializations.length!==5||v.specializations.some(s=>!s||!['impact','control'].every(k=>Number.isInteger(s[k])&&s[k]>=0&&s[k]<=3)))throw Error('Invalid upgrades.');const c=new CampaignState();Object.assign(c,{level:v.level,highest:v.highest,completed:v.completed,unlocked:v.unlocked,specializations:v.specializations,mastery:integers(v.mastery,6)?v.mastery:[],time:Number.isFinite(v.time)?Math.max(0,v.time):0,deaths:Number.isInteger(v.deaths)?Math.max(0,v.deaths):0});if(c.spent>c.earned)throw Error('Upgrade points exceed earned points.');if(v.snapshot){const s=v.snapshot;if(s.level!==v.level||!Number.isInteger(s.checkpoint)||s.checkpoint<0||s.checkpoint>5||!Array.isArray(s.gates)||!Array.isArray(s.encounters))throw Error('Invalid checkpoint.');c.snapshot={level:s.level,checkpoint:s.checkpoint,gates:s.gates.filter(x=>Number.isInteger(x)&&x>=0&&x<5),encounters:s.encounters.filter(x=>Number.isInteger(x)&&x>=0&&x<3),shrine:!!s.shrine,signature:!!s.signature};}return c;}
 }
 class CampaignGame{
  constructor(campaign=new CampaignState(),options={}){this.campaign=campaign;this.mode=options.mode||(options.demo?'demo':'campaign');this.showcase=this.mode==='showcase';this.demo=!!options.demo||this.showcase;this.showcaseStage=0;this.demoTier=clamp(options.tier||1,1,7);this.events=[];this.accumulator=0;this.loadLevel(options.level??campaign.level,!this.demo);}
  event(type,data={}){this.events.push({type,...data});}
  get tier(){return this.demo?this.demoTier:this.level.id+1;}get specs(){return this.demo?Array.from({length:5},()=>({impact:this.showcase&&this.tier===7?3:0,control:this.showcase&&this.tier===7?3:0})):this.campaign.specializations;}
  get currentGate(){return this.gates.find(g=>!g.open);}get currentOrb(){return this.orbs.find(o=>!o.collected);}get progress(){return (this.encounters.filter(e=>e.done).length+this.gates.filter(g=>g.open).length+(this.boss?.hp<=0?1:0))/(this.encounters.length+this.gates.length+1);}
  get checkpointReady(){return dist(this.player,this.checkpoint)<9&&!this.inCombat;}get inCombat(){return !this.finished&&(this.encounters.some(e=>e.started&&!e.done)||this.shrine.active||this.boss.active&&this.boss.hp>0||this.enemies.some(e=>e.hp>0&&e.active&&dist(e,this.player)<48));}
  loadLevel(id,resume=false){if(!Number.isInteger(id)||id<0||id>6)throw Error('Unknown level');this.level=this.showcase?showcaseLevel:levels[id];this.time=0;this.finished=false;this.player={x:this.level.centerAt(8),z:8,y:0,dx:0,dz:1,hp:100,maxHp:100,invincible:0,moving:0};this.castAnim=0;this.swordAnim=0;this.combo=0;this.comboExpiry=0;this.shield=0;this.nextCast=0;this.nextTempest=0;this.nextSword=0;this.nextField=0;this.view=null;this.lifeId=(this.lifeId||0)+1;this.lastInput={};this.projectiles=[];this.covers=[];this.pendingSword=null;this.finishReady=false;this.finishArmed=false;this.endingAt=0;this.attackId=0;this.airPrimedUntil=0;this.fields=[];this.telegraphs=[];this.enemies=[];this.nextId=1;this.targetId=null;this.checkpointIndex=0;this.checkpoint={x:this.level.centerAt(8),z:8};this.accumulator=0;this.pendingActions={};this.combatSeed=(0x71a52d3+id)>>>0;this.unlocks=new Set(this.demo?[0,1,2,3,4]:this.campaign.unlocked);this.element=this.unlocks.has(1)?1:[...this.unlocks][0]??1;
   this.gates=this.level.puzzles.map(([z,type,label],i)=>({id:i,x:this.level.centerAt(z),z,type,label,hp:48,max:48,open:false,kind:'gate'}));
   this.orbs=id===0?[1,0,2,3,4].map((type,i)=>({x:this.level.centerAt(this.level.discoveryZ[i]),z:this.level.discoveryZ[i],type,collected:this.unlocks.has(type)})):[];
   this.encounters=this.level.encounters.map((z,id)=>({id,x:this.level.centerAt(z),z,wave:0,done:false,started:false}));this.shrine={...this.level.shrine,active:false,done:this.campaign.mastery.includes(id),wave:0};
   this.obstacles=[];for(let j=0;j<Math.floor((this.level.length-55)/43);j++){const z=55+j*43;if(this.gates.some(g=>Math.abs(g.z-z)<20)||this.level.encounters.some(e=>Math.abs(e-z)<28)||this.level.ramps.some(r=>z>r.start-5&&z<r.start+r.length+5)||Math.abs(z-this.level.shrine.z)<20)continue;this.obstacles.push({x:(j%2?-10:10)+this.level.centerAt(z),z,w:3.5,d:3.5,h:2.5});}
   this.barrels=this.level.theme==='west'?Array.from({length:6},(_,i)=>({id:i,x:(i%2?8:-8)+this.level.centerAt(105+Math.floor(i/2)*148),z:105+Math.floor(i/2)*148,hp:1})):[];
   this.relays=this.level.id===2?[[-7,-18],[0,-12],[7,-18]].map(([x,z],i)=>({id:"relay"+i,x:x+this.level.centerAt(this.level.bossZ),z:this.level.bossZ+z,hp:60,max:60,kind:"relay",radius:1.8})):[];if(this.relays.length)this.obstacles=this.obstacles.filter(o=>o.z<this.level.bossTrigger-12);
   this.boss=this.makeEnemy(this.level.centerAt(this.level.bossZ),this.level.bossZ,'boss',-1);this.boss.active=false;this.boss.hp=this.boss.max=(id===6?1250:1000)*damageScale[id];this.boss.phase=1;this.boss.cycle=0;this.boss.cooldown=3;this.boss.name=this.level.boss;
   this.signature={z:this.showcase?100:(id===0?480:290),charge:0,done:!!(resume&&this.campaign.snapshot?.signature),phase:0};if(!this.demo){this.campaign.level=id;if(id>0)[0,1,2,3,4].forEach(i=>this.unlocks.add(i));this.campaign.unlocked=[...this.unlocks];const snap=resume?this.campaign.snapshot:null;if(snap&&snap.level===id){for(const i of snap.gates)if(this.gates[i])this.gates[i].open=true;for(const i of snap.encounters)if(this.encounters[i])this.encounters[i].done=true;this.shrine.done=snap.shrine;this.checkpointIndex=snap.checkpoint;this.checkpoint={x:this.level.centerAt(this.level.checkpoints[snap.checkpoint]),z:this.level.checkpoints[snap.checkpoint]};this.player.z=this.checkpoint.z;this.player.x=this.checkpoint.x;}this.saveCheckpoint(false);}
   if(this.showcase){this.gates=[];this.orbs=[];this.shrine.done=true;this.demoTier=[1,4,7][this.showcaseStage];for(const e of this.encounters)if(e.id<this.showcaseStage)e.done=true;this.player.z=[8,75,145][this.showcaseStage];this.player.x=this.level.centerAt(this.player.z);this.boss.hp=this.boss.max=7000;}this.events=[];this.event('level',{id,tier:this.tier});
  }
  random(){this.combatSeed=(Math.imul(this.combatSeed,1664525)+1013904223)>>>0;return this.combatSeed/4294967296;}
  get airCritChance(){return .25+(this.tier-1)*.025;}
  rollCritical(){return this.canUse(0)&&this.element===0&&this.random()<this.airCritChance;}
  canUse(i){return i>=0&&i<5&&(this.demo||this.unlocks.has(i));}
  select(i){if(!this.canUse(i)){this.event('notice',{text:'Find the '+elements[i]?.name+' crystal.'});return false;}this.element=i;this.event('switch',{element:i});return true;}
  walkHeight(x,z){if(Math.abs(x-this.level.centerAt(z))>17)return 0;for(const r of this.level.ramps)if(z>=r.start&&z<=r.start+r.length)return Math.max(0,Math.min(r.height,(z-r.start)/r.rise*r.height,(r.start+r.length-z)/r.rise*r.height));return 0;}
  validPosition(x,z,oldZ,radius=.7){const cx=this.level.centerAt(z),margin=Math.max(0,radius-.7);x=clamp(x,cx-20+margin,cx+(Math.abs(z-this.level.shrine.z)<30?40:20)-margin);for(const g of this.gates)if(!g.open&&oldZ<g.z&&z>g.z-3)z=g.z-3;for(const e of this.encounters)if(!e.done&&oldZ<e.z+42&&z>e.z+42)z=e.z+42;for(const o of this.obstacles)if(Math.abs(x-o.x)<o.w+radius&&Math.abs(z-o.z)<o.d+radius){const dx=(o.w+radius)-Math.abs(x-o.x),dz=(o.d+radius)-Math.abs(z-o.z);if(dx<dz)x=o.x+Math.sign(x-o.x||1)*(o.w+radius+.01);else z=o.z+Math.sign(z-o.z||1)*(o.d+radius+.01);}return {x,z:clamp(z,3,this.level.length-6)};}
  visibleTarget(e,p=this.player){if(this.gates.some(g=>!g.open&&(p.z-g.z)*(e.z-g.z)<0))return false;for(const o of this.obstacles){const dx=e.x-p.x,dz=e.z-p.z,d=dx*dx+dz*dz,u=((o.x-p.x)*dx+(o.z-p.z)*dz)/(d||1);if(u>.03&&u<.97&&Math.abs(p.x+dx*u-o.x)<o.w&&Math.abs(p.z+dz*u-o.z)<o.d)return false;}return true;}
  inView(e){const v=this.view;if(!v)return true;const x=e.x-v.x,z=e.z-v.z,depth=x*v.dx+z*v.dz;return depth>0&&Math.abs(x*v.dz-z*v.dx)<depth*v.tan+1.5;}
  acquireTarget(facing={x:0,z:1},cycle=false){const p=this.player;let candidates=[...this.enemies.filter(e=>e.hp>0&&e.active),...this.relays.filter(e=>e.hp>0&&this.boss.active)].filter(e=>dist(e,p)<=32&&this.visibleTarget(e)&&this.inView(e));if(this.relays.some(r=>r.hp>0)&&this.boss.active){const pylons=candidates.filter(e=>e.kind==='relay');if(pylons.length)candidates=pylons;}const score=e=>dist(e,p)+10*(1-((e.x-p.x)*facing.x+(e.z-p.z)*facing.z)/(dist(e,p)||1));candidates.sort((a,b)=>score(a)-score(b));let chosen=candidates.find(e=>e.id===this.targetId);if(cycle&&candidates.length)chosen=candidates[(candidates.indexOf(chosen)+1)%candidates.length];else chosen=chosen||candidates[0];this.targetId=chosen?.id??null;if(chosen)return chosen;const gate=this.currentGate;if(gate&&dist(gate,p)<=32)return gate;return null;}
  makeEnemy(x,z,role='melee',encounter=0){if(role==='boss')({x,z}=this.validPosition(x,z,z,3));const factor=[1,1.15,1.35,1.6,1.8,2.1,2.4][this.level.id],hp={melee:105,ranged:80,shield:140,support:75,boss:1000}[role]*factor;const e={id:this.nextId++,x,z,homeZ:z,role,encounter,kind:'enemy',weakness:role==='boss'?[2,3,2,3,1,4,0][this.level.id]:role==='shield'?4:role==='ranged'?0:role==='support'?2:(this.nextId+this.level.id)%2?1:3,hp,max:hp,active:true,attackUntil:0,cooldown:1.2+(this.nextId%4)*.3,status:{},stagger:0,hit:0,phase:1};this.enemies.push(e);return e;}
  spawnWave(encounter,shrine=false){const wave=++encounter.wave,n=shrine?4:this.level.waveSize;for(let i=0;i<n;i++){const role=['melee','ranged','shield','melee','support','ranged'][(i+wave-1)%6],a=i/n*Math.PI*2;const foe=this.makeEnemy((shrine?this.level.shrine.x:this.level.centerAt(encounter.z))+Math.sin(a)*(shrine?4:13),encounter.z+Math.cos(a)*15,role,shrine?9:encounter.id);if(this.showcase&&!shrine)foe.hp=foe.max=foe.max*[1.4,3.2,5][encounter.id];}this.event('encounterstart',{id:encounter.id});this.event('wave',{wave,text:shrine?'Mastery trial':`Encounter ${encounter.id+1} · wave ${wave}/${this.level.waves}`});}
  saveCheckpoint(emit=true){if(this.demo)return;this.campaign.snapshot={level:this.level.id,checkpoint:this.checkpointIndex,gates:this.gates.filter(g=>g.open).map(g=>g.id),encounters:this.encounters.filter(e=>e.done).map(e=>e.id),shrine:this.shrine.done,signature:!!this.signature?.done};this.campaign.unlocked=[...this.unlocks];if(emit)this.event('save');}
  recordDamage(e,before,element,critical=false){const amount=before-e.hp;if(amount>0)this.event('damage',{id:e.id,amount,element,critical,weak:e.weakness===element,x:e.x,y:this.walkHeight(e.x,e.z)+(e.role==='boss'?8.4:4.8),z:e.z});}
  hit(e,amount,el,allowReaction=true,applyStatus=true,critical=false,profile=null){if(e.hp<=0)return;const boss=e.role==='boss',tier=profile?.tier||this.tier,spec=profile?.spec||this.specs[el];if(boss&&this.relays.some(r=>r.hp>0)){this.event('notice',{text:'Destroy the three relay pylons to expose the core.'});return;}if(e.kind==='relay'){const before=e.hp;e.hp=Math.max(0,e.hp-amount);this.recordDamage(e,before,el,critical);if(e.hp<=0)this.event('impact',{x:e.x,z:e.z,element:2});return;}
   if(e.weakness===el)amount*=1.5;
   const status=e.status;if(allowReaction&&this.canUse(el)){let reaction=null;if(el===2&&status.wet>this.time)reaction='Conduct';if(el===0&&status.burn>this.time)reaction='Wildfire';if((el===1&&status.wet>this.time)||(el===3&&status.burn>this.time))reaction='Steam';if((el===1&&status.stone>this.time)||(el===4&&status.burn>this.time))reaction='Molten';if(reaction&&(status.reaction||0)<this.time){status.reaction=this.time+.8;this.event('reaction',{name:reaction,x:e.x,z:e.z,element:el});if(boss)e.stagger+=20;else this.disableEnemy(e,.6);for(const other of this.enemies)if(other!==e&&other.hp>0&&other.active!==false&&this.visibleTarget(other)&&dist(other,e)<(reaction==='Conduct'?13:7)){this.hit(other,amount*.55,el,false);if(reaction==='Wildfire')other.status.burn=status.burn;}amount*=1.4;}}
   if(e.role==='shield'&&!(status.stun>this.time)&&!(status.broken>this.time)&&![0,4].includes(el))amount*=.45;
   if(boss&&this.showcase&&this.finishReady)return;const before=e.hp;e.hp=Math.max(0,e.hp-amount);if(boss&&this.showcase&&e.hp<=0){e.hp=1;this.finishReady=true;this.telegraphs=[];this.fields=[];e.status.stun=this.time+999;this.event('finishready');}this.recordDamage(e,before,el,critical);e.hit=.18;e.hitElement=el;e.hitDX=(e.x-this.player.x)/(dist(e,this.player)||1);e.hitDZ=(e.z-this.player.z)/(dist(e,this.player)||1);const duration=(2+tier*.22)*(1+spec.control*.15);if(applyStatus&&el===1)status.burn=this.time+duration;if(applyStatus&&el===3)status.wet=this.time+duration;if(applyStatus&&el===4)status.stone=this.time+duration;if(el===0&&!boss){const d=dist(e,this.player)||1;e.x+=clamp((e.x-this.player.x)/d*.5,-.5,.5);e.z+=clamp((e.z-this.player.z)/d*.5,-.5,.5);if(tier>=4)this.disableEnemy(e,.18*(1+spec.control*.15));}if(applyStatus&&el===2&&this.time>=(status.paralyzeReady||0)){if(boss)e.stagger+=12;else{this.disableEnemy(e,(.65+tier*.05)*(1+spec.control*.15));}status.paralyzeReady=this.time+2;}if(boss){e.stagger+=amount*.018;if(e.stagger>=100){e.stagger=0;status.stun=this.time+2.5;this.telegraphs=this.telegraphs.filter(t=>t.owner!==e.id);this.event('notice',{text:'Guardian staggered — strike now!'});}}else if(applyStatus&&el===4){this.disableEnemy(e,.3*(1+spec.control*.15));status.broken=this.time+3;}if(applyStatus&&el===4)this.shield=Math.max(this.shield,.8);
   this.event('impact',{id:e.id,x:e.x,z:e.z,element:el,strength:Math.min(1,amount/45),attackId:this.resolvingAttack||null});if(e.hp<=0){if(el===3||status.wet>this.time)this.player.hp=Math.min(100,this.player.hp+10);this.event('defeat',{id:e.id,x:e.x,z:e.z,element:el});if(boss)this.complete();else if(status.burn>this.time){
    // Corpses cannot be hit twice, so a chain consumes each enemy at most once.
    this.event('ignition',{x:e.x,z:e.z,element:1,tier:tier});
    const radius=6*Math.min(1.8,1+this.specs[1].control*.15);
    for(const other of this.enemies)if(other!==e&&other.hp>0&&other.active!==false&&dist(other,e)<radius&&this.visibleTarget(other)&&this.visibleTarget(other,e))this.hit(other,12*damageScale[tier-1]*(1+this.specs[1].impact*.15),1,false);
   }}
  }
  cast(target,ultimate=false,sword=false){if(this.finished||(!sword&&!this.canUse(this.element)))return false;if(this.showcase&&this.finishReady&&this.finishArmed&&!sword){this.boss.hp=0;this.recordDamage(this.boss,1,this.element);this.finishReady=false;this.finishArmed=false;this.endingAt=this.time+2.5;this.event('finale',{element:this.element,x:this.boss.x,z:this.boss.z,tier:7,dx:0,dz:1});return true;}if(sword)return this.beginSword(target);const p=this.player,el=this.element,tier=this.tier,spec=this.specs[el],critical=el===0&&this.airPrimedUntil>this.time?(this.airPrimedUntil=0,true):this.rollCritical();let dx=target?target.x-p.x:p.dx,dz=target?target.z-p.z:p.dz,d=Math.hypot(dx,dz)||1;dx/=d;dz/=d;p.dx=dx;p.dz=dz;if(!sword)this.castAnim=.23;
   const damage=(ultimate?4:8)*damageScale[tier-1]*(1+spec.impact*.15),range=32,area=(ultimate?12:1.25)*(1+spec.control*.15),tx=target?target.x:p.x+dx*20,tz=target?target.z:p.z+dz*20;
   const reach=Math.min(range,Math.max(target?d+4:27,16)),spread=Math.min(1.8,(1+(tier-1)*.075)*(1+spec.control*.15)),hitTargets=[];
   this.event('cast',{x:p.x+dx*.8,y:p.y,z:p.z+dz*.8,dx,dz,element:el,ultimate,sword,combo:sword?this.combo:0,tier,specialization:copy(spec),range:el===2?(target?Math.min(32,d):27):reach,targets:hitTargets,impactX:tx,impactZ:tz,critical});
   if(ultimate&&el===4){this.shield=1.2;if(!this.covers.length)this.covers.push({x:p.x+dx*3.5,z:p.z+dz*3.5,dx,dz,life:2.5,r:3.5});}this.interactWorld(el,{x:tx,z:tz});
   if(target?.kind==='gate'&&dist(p,target)<range&&!sword){if(el===target.type){target.hp=Math.max(0,target.hp-damage);if(target.hp===0){target.open=true;this.event('opened',{element:el,x:target.x,z:target.z,text:target.label});this.saveCheckpoint();}}else this.event('notice',{text:elements[target.type].name+' is needed here.'});}
   // Resolve the complete footprint before applying knockback or reactions.
   const foes=[...this.enemies,...this.relays].filter(e=>e.hp>0&&e.active!==false&&(e.kind!=='relay'||this.boss.active)&&dist(e,p)<=range&&this.visibleTarget(e));
   const direct=foes.filter(e=>{const vx=e.x-p.x,vz=e.z-p.z,along=vx*dx+vz*dz,across=Math.abs(vx*dz-vz*dx),distance=dist(e,p);
    if(ultimate)return dist(e,{x:tx,z:tz})<area;
    if(e===target)return true;
    if(along<0||along>reach)return false;
    if(el===2)return dist(e,{x:tx,z:tz})<=7*spread;
    const width=[6,4.5,0,9,5.5][el]*spread;
    return across<=width*(el===3||el===4?1:.35+.65*along/reach);
   });
   for(const e of direct){hitTargets.push({x:e.x,z:e.z,y:this.walkHeight(e.x,e.z)+2});this.hit(e,damage*(critical?2:1),el,true,this.canUse(el),critical);}
   if(!sword&&tier>=2&&target?.kind==='enemy'){
    const candidates=foes.filter(e=>e!==target&&!direct.includes(e)&&e.hp>0&&dist(e,target)<(el===2?12:8)*spread).sort((a,b)=>dist(a,target)-dist(b,target));
    for(const other of candidates.slice(0,el===2?Math.min(4,tier-1):1)){this.hit(other,damage*(el===2?.5:.3)*(critical?2:1),el,false,true,critical);hitTargets.push({x:other.x,z:other.z,y:this.walkHeight(other.x,other.z)+2});this.event('chain',{x:target.x,z:target.z,tx:other.x,tz:other.z,element:el});}
   }
   if(!sword&&(tier>=3||el===3)&&this.time>=(this.nextField||0)){this.nextField=this.time+.55;this.fields.push({x:tx,z:tz,element:el,life:2.3*(1+spec.control*.15),tick:0,r:(ultimate?7:3)*(1+spec.control*.15),damage:damage*.13,tier});if(this.fields.length>12)this.fields.shift();}
   if(!sword&&tier>=6&&target?.kind==='enemy')this.fields.push({x:tx,z:tz,element:el,life:.75,tick:-.2,r:4,damage:damage*.4,tier});if(this.fields.length>16)this.fields.splice(0,this.fields.length-16);
   for(const b of this.barrels)if(b.hp>0&&dist(b,{x:tx,z:tz})<6&&[1,2].includes(el)){b.hp=0;this.event('reaction',{name:'Detonation',x:b.x,z:b.z,element:1});for(const e of this.enemies)if(e.hp>0&&dist(e,b)<12)this.hit(e,120*damageScale[tier-1],1,false);}
   return true;
  }
  damage(amount){if(this.finished)return;const p=this.player;if(p.invincible>0)return;p.hp-=amount*(this.shield>0?.6:1);p.invincible=.6;if(this.pendingSword){this.pendingSword=null;this.swordAnim=0;this.combo=0;this.nextSword=this.time+.12;this.event('swordinterrupt');}this.event('hurt');if(p.hp<=0)this.respawn();}
  respawn(){this.campaign.deaths+=this.demo?0:1;const events=this.events;this.loadLevel(this.level.id,!this.demo);this.player.invincible=2;this.events=events;this.event('respawn');}
  telegraph(e,kind,r=5,delay=.9){const boss=e.role==='boss',owners=new Set(this.telegraphs.filter(t=>this.enemies.find(n=>n.id===t.owner)?.role!=='boss').map(t=>t.owner)),major=this.telegraphs.some(t=>this.enemies.find(n=>n.id===t.owner)?.role==='boss');if(!boss&&(owners.has(e.id)||owners.size>=(major?1:2)))return false;if(boss&&owners.size>1){const keep=[...owners][0];this.telegraphs=this.telegraphs.filter(t=>t.owner===keep||this.enemies.find(n=>n.id===t.owner)?.role==='boss');}delay=Math.max(delay,boss?1.2:.9);const p=this.player,origin=['ring','fan','beam'].includes(kind);this.telegraphs.push({owner:e.id,kind,x:origin?e.x:p.x,z:origin?e.z:p.z,ox:e.x,oz:e.z,r,life:delay,max:delay,dx:p.x-e.x,dz:p.z-e.z});e.attackUntil=this.time+delay;e.attackKind=kind;this.event('warning',{id:e.id,x:e.x,z:e.z,kind,boss});if(this.telegraphs.length>30)this.telegraphs.shift();return true;}
  enemyStep(e,dt){if(e.hp<=0||!e.active)return;e.hit=Math.max(0,e.hit-dt);if(e.status.burn>this.time&&this.time>=(e.status.burnTick||0)){e.status.burnTick=this.time+.6;this.hit(e,2*damageScale[this.tier-1],1,false,false);if(e.hp<=0)return;}if(e.status.stun>this.time||e.recoverUntil>this.time)return;const p=this.player,d=dist(e,p);if(d>65)return;e.cooldown-=dt;
   if(e.role==='boss'){if(d<7&&e.attackUntil<=this.time){const away=this.validPosition(e.x+(e.x-p.x)/(d||1)*4.5*dt,e.z+(e.z-p.z)/(d||1)*4.5*dt,e.z,3);e.x=away.x;e.z=away.z;}if([0,4,5,6].includes(this.level.id)&&d>11){const next=this.validPosition(e.x+(p.x-e.x)/(d||1)*2.6*dt,e.z+(p.z-e.z)/(d||1)*2.6*dt,e.z,3);e.x=next.x;e.z=next.z;}if(e.hp<e.max*.5&&e.phase===1){e.phase=2;this.event('bossphase',{name:e.name});}if(e.cooldown<=0){e.cycle++;e.cooldown=e.phase===2?2.1:3.1;const style=this.level.id===6?e.cycle%6:this.level.id;
     if(style===0){this.telegraph(e,'ring',8,1);if(e.cycle%3===0&&(e.summons||0)<3&&this.enemies.filter(n=>n.hp>0).length<15){e.summons=(e.summons||0)+1;this.makeEnemy(e.x-8,e.z-4,'melee',8);this.makeEnemy(e.x+8,e.z-4,'shield',8);}}
     if(style===1){this.telegraph(e,'fan',11,.9);e.recoverUntil=this.time+.3;}
     if(style===2){this.telegraph(e,'strike',7,.85);if(e.phase===2)this.telegraph(e,'ring',12,1.2);}
     if(style===3){this.telegraph(e,'beam',6,1.1);this.telegraph(e,'strike',5,1.5);}
     if(style===4){this.telegraph(e,'fan',12,1);if(e.phase===2)this.telegraph(e,'charge',6,.85);}
     if(style===5){this.telegraph(e,'charge',6,.9);this.telegraph(e,'ring',14,1.5);}
    }return;}
   if(e.role==='support'){if(e.cooldown<=0){e.cooldown=6;for(const other of this.enemies)if(other!==e&&other.hp>0&&other.role!=='boss'&&dist(e,other)<18)other.hp=Math.min(other.max,other.hp+other.max*.07);this.event('support',{x:e.x,z:e.z});}}
   else if(e.cooldown<=0){e.cooldown=e.role==='ranged'?2.8:2.2;this.telegraph(e,e.role==='ranged'?'strike':'melee',e.role==='ranged'?2.4:2.2,.85);}
   if(e.attackUntil>this.time)return;const desired=e.role==='ranged'||e.role==='support'?16:3,approach=d>desired?1:d<desired-3?-.6:0,strafe=e.role==='shield'?0:Math.sin(this.time*.7+e.id)*.45;const dx=(p.x-e.x)/(d||1),dz=(p.z-e.z)/(d||1),speed=(e.role==='shield'?2:3.2)*(this.tier>=4&&(e.status.wet>this.time||e.status.burn>this.time)?.8:1);const next=this.validPosition(e.x+(dx*approach+dz*strafe)*speed*dt,e.z+(dz*approach-dx*strafe)*speed*dt,e.z);if(approach>0&&Math.hypot(next.x-e.x,next.z-e.z)<dt*.4){const detour=this.validPosition(e.x+(e.id%2?1:-1)*speed*dt,e.z,e.z);next.x=detour.x;}e.x=next.x;e.z=clamp(next.z,e.homeZ-34,e.homeZ+34);
  }
  complete(){if(this.finished)return;this.finished=true;if(!this.demo){const c=this.campaign,id=this.level.id;if(!c.completed.includes(id))c.completed.push(id);c.highest=Math.min(6,Math.max(c.highest,id+1));c.snapshot=null;this.event('save');}this.event('complete',{level:this.level.id,final:this.level.id===6});}
  advance(dt,input={}){
   // Preserve brief presses when a render frame is shorter than the fixed simulation tick.
   for(const key of ['cycle','cast','tempest','sword'])if(input[key])this.pendingActions[key]=true;
   if(input.select!==undefined)this.pendingActions.select=input.select;
   this.accumulator+=Math.min(.2,Math.max(0,dt));let n=0;
   while(this.accumulator>=1/60&&n++<12){const tickInput={...input,...this.pendingActions};this.pendingActions={};this.accumulator-=1/60;this.step(1/60,tickInput);input={...input,cycle:false};}
  }
  step(dt,input={}){if(this.finished)return;this.view=input.view||this.view;this.time+=dt;if(!this.demo)this.campaign.time+=dt;const lifeId=this.lifeId,p=this.player;for(const key of ['castAnim','swordAnim','shield'])this[key]=Math.max(0,this[key]-dt);p.invincible=Math.max(0,p.invincible-dt);
   if(input.select!==undefined)this.select(input.select);
   let mx=Number(input.mx)||0,mz=Number(input.mz)||0,n=Math.hypot(mx,mz);if(n>1){mx/=n;mz/=n;}if(n>.01){p.dx=mx/(Math.hypot(mx,mz)||1);p.dz=mz/(Math.hypot(mx,mz)||1);}p.moving=Math.min(1,n);const next=this.validPosition(p.x+mx*13*dt,p.z+mz*13*dt,p.z);p.x=next.x;p.z=next.z;p.y=this.walkHeight(p.x,p.z);
   const orb=this.currentOrb;if(orb&&p.z>=orb.z-6&&!this.gates.some(g=>!g.open&&g.z<orb.z)&&this.visibleTarget(orb)){orb.collected=true;this.unlocks.add(orb.type);this.element=orb.type;this.event('unlocked',{element:orb.type,tier:1});this.saveCheckpoint();}
   if(this.finishReady&&!input.cast&&!input.tempest)this.finishArmed=true;this.swordStep();this.worldStep(dt);const target=input.manualTarget||this.acquireTarget({x:p.dx,z:p.dz},input.cycle);if(input.cast&&(!this.lastInput.cast||this.time>=this.nextCast)){this.cast(target);this.nextCast=this.time+.14;}if(input.tempest&&(!this.lastInput.tempest||this.time>=this.nextTempest)){this.cast(target,true);this.nextTempest=this.time+.2;}if(input.sword&&this.time>=this.nextSword){this.cast(target,false,true);this.nextSword=this.time+this.swordDuration;}this.lastInput={cast:!!input.cast,tempest:!!input.tempest};
   for(const encounter of this.encounters)if(!encounter.done&&p.z>encounter.z-(this.showcase?22:38)){if(!encounter.started){encounter.started=true;this.spawnWave(encounter);}else if(!this.enemies.some(e=>e.encounter===encounter.id&&e.hp>0&&e.role!=='boss')){if(encounter.wave<this.level.waves)this.spawnWave(encounter);else{encounter.done=true;this.event('encounterclear',{id:encounter.id});if(this.showcase&&encounter.id<2){this.showcaseStage=encounter.id+1;this.demoTier=[1,4,7][this.showcaseStage];this.player.hp=100;this.event('transformation',{tier:this.tier});}this.event('notice',{text:'Encounter cleared. The path is open.'});this.saveCheckpoint();}}}
   if(!this.shrine.done&&dist(this.shrine,p)<6&&!this.shrine.active){this.shrine.active=true;this.spawnWave({id:9,z:this.shrine.z,wave:0},true);}if(this.shrine.active&&!this.enemies.some(e=>e.encounter===9&&e.hp>0)){this.shrine.done=true;this.shrine.active=false;p.hp=100;if(!this.demo&&!this.campaign.mastery.includes(this.level.id))this.campaign.mastery.push(this.level.id);this.event('mastery');this.saveCheckpoint();}
   if(p.z>this.level.bossTrigger&&this.encounters.every(e=>e.done)&&this.gates.every(g=>g.open)&&!this.boss.active){this.boss.active=true;this.event('boss',{name:this.boss.name});}
   for(const e of this.enemies)this.enemyStep(e,dt);
   for(const f of this.fields){f.life-=dt;f.tick+=dt;if(f.tick>.35){f.tick=0;for(const e of this.enemies)if(e.hp>0&&e.active&&this.visibleTarget(e)&&dist(e,f)<f.r){this.hit(e,f.damage,f.element,false);if(f.element===3&&e.role!=='boss'){const pull=this.validPosition(e.x+(f.x-e.x)*.08,e.z+(f.z-e.z)*.08,e.z);e.x=pull.x;e.z=pull.z;}}}}this.fields=this.fields.filter(f=>f.life>0);
   for(const t of this.telegraphs){t.life-=dt;if(t.life<=0){const owner=this.enemies.find(e=>e.id===t.owner);if(!owner||owner.hp<=0)continue;let hit=false;if(t.kind==='ring')hit=Math.abs(dist(p,t)-t.r)<2.2;else if(t.kind==='melee')hit=dist(p,t)<t.r;else if(t.kind==='charge'){hit=dist(p,t)<t.r;const v=this.validPosition(t.x,t.z,owner.z,owner.role==='boss'?3:.7);owner.x=v.x;owner.z=v.z;}else if(t.kind==='fan'||t.kind==='beam'){const d=Math.hypot(t.dx,t.dz)||1,dx=t.dx/d,dz=t.dz/d,vx=p.x-t.x,vz=p.z-t.z,along=vx*dx+vz*dz,across=Math.abs(vx*dz-vz*dx);hit=along>0&&along<32&&across<(t.kind==='fan'?along*.52:2.3);}else hit=dist(p,t)<t.r;owner.followThrough=this.time+.3;this.event('enemyattack',{...t});if(hit&&this.visibleTarget(owner)&&!this.coverBlocks(owner,p,t.kind))this.damage(owner.role==='boss'?20:10);if(this.lifeId!==lifeId)return;}}this.telegraphs=this.telegraphs.filter(t=>t.life>0);
   if(this.level.id===4&&!this.signature.done&&p.z>this.level.blizzard.start&&p.z<this.level.blizzard.end&&Math.abs(p.x-this.level.centerAt(p.z))<7&&this.shield<=0&&Math.floor(this.time)%3===0)this.damage(5);
   for(let i=this.checkpointIndex+1;i<this.level.checkpoints.length;i++)if(p.z>=this.level.checkpoints[i]&&!this.inCombat){this.checkpointIndex=i;this.checkpoint={x:this.level.centerAt(this.level.checkpoints[i]),z:this.level.checkpoints[i]};p.hp=100;this.saveCheckpoint();this.event('checkpoint',{index:i});}
   if(this.lifeId!==lifeId)return;if(this.enemies.length>100)this.enemies=this.enemies.filter(e=>e.hp>0||e.role==='boss'||Math.abs(e.z-p.z)<55);
  }
 }
 const api={CampaignState,CampaignGame,LevelDefinition,levels,elements,damageScale,tierFeatures,powerNames,SAVE_KEY,clamp,dist};if(typeof module!=='undefined'&&module.exports){module.exports=api;require('./combat-system.js')(api);}else {root.SevenWorlds=api;root.Fivefold3D={elements,clamp};}
})(typeof window==='undefined'?this:window);
