/* Browser application. Rendering and sound consume deterministic combat events. */
(()=>{'use strict';
const T=THREE,{CampaignGame,CampaignState,levels,elements,damageScale,tierFeatures,powerNames,SAVE_KEY,clamp,dist}=SevenWorlds,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let campaign=new CampaignState(),stored=false,saveError='';try{const raw=localStorage.getItem(SAVE_KEY);if(raw){campaign=CampaignState.parse(raw);stored=true;}}catch(e){saveError='The stored save could not be read. Import an exported save or start a new game.';}
let renderer;try{renderer=new T.WebGLRenderer({canvas:$('#world'),antialias:false,powerPreference:'high-performance'});}catch(e){$('#unsupported').textContent='WebGL could not start. Enable hardware acceleration in your browser.';$('#unsupported').classList.remove('hidden');return;}
renderer.outputColorSpace=T.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.info.autoReset=false;
const scene=new T.Scene(),camera=new T.PerspectiveCamera(58,innerWidth/innerHeight,.12,260),cinema=new CinematicView(renderer,scene,camera),hero=createActionHero(),heroRoot=new T.Group();heroRoot.add(hero.root);scene.add(heroRoot);
const ambient=new T.HemisphereLight('#bfd3df','#25232a',1.5),sun=new T.DirectionalLight('#cdd5dc',2.1),rim=new T.DirectionalLight('#bddaea',1.4);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-35,right:35,top:45,bottom:-25,near:.5,far:110});sun.shadow.bias=-.001;scene.add(ambient,sun,sun.target,rim,rim.target);
const gl=renderer.getContext(),debugInfo=gl.getExtension('WEBGL_debug_renderer_info'),adapter=debugInfo?gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL):'WebGL adapter unavailable';
const damageNumbers=new DamageNumbers($('#damageNumbers'));const swordTrail=new SwordMotion.SwordTrail(scene);const fx=new ElementEffects(scene),mastery=new MasteryFX(scene),audio=new ElementAudio();let game=new CampaignGame(new CampaignState(),{demo:true,level:0,tier:1}),world=new WorldView(scene,game),ready=false,running=false,paused=true,replay=false,selectionMode='replay',upgradesReturn='menu',time=0,last=performance.now(),fps=60,statsTime=0,frameCount=0,frameTotal=0,autoSamples=0,quality='high',cameraYaw=0,cameraPitch=.39,cameraDistance=13,mouseDown=false,queuedDash=false,queuedCycle=false,toastUntil=0,titleUntil=0,uiTime=0,musicCombatUntil=0,settings={music:.55,effects:.75,reduced:false,quality:'auto',stats:false},keys=new Set(),enemyViews=new Map(),enemyPool=[];
const sharedGeo=new Set(),sharedMat=new Set(),warnGeo=new T.RingGeometry(.94,1,60),warnMat=new T.MeshBasicMaterial({color:'#df7055',side:T.DoubleSide,transparent:true,opacity:.6,depthWrite:false}),warnings=[];for(let i=0;i<30;i++){const g=new T.Group(),ring=new T.Mesh(warnGeo,warnMat),fill=new T.Mesh(new T.CircleGeometry(1,40),new T.MeshBasicMaterial({color:'#d85c3c',side:T.DoubleSide,transparent:true,opacity:.1,depthWrite:false}));ring.rotation.x=fill.rotation.x=-Math.PI/2;g.add(ring,fill);g.visible=false;scene.add(g);warnings.push(g);}
const warningCircle=warnings[0].children[1].geometry;const warningFanShape=new T.Shape();warningFanShape.moveTo(0,0);warningFanShape.lineTo(-16.64,-32);warningFanShape.lineTo(16.64,-32);warningFanShape.closePath();const warningFan=new T.ShapeGeometry(warningFanShape),warningBeam=new T.PlaneGeometry(4.6,32);
const touch=new TouchControls({canvas:$('#world'),onLook:(x,y)=>{if(!paused){cameraYaw-=x*.006;cameraPitch=clamp(cameraPitch+y*.003,.15,.95);}},onCycle:()=>queuedCycle=true,onDash:()=>queuedDash=true});
try{const s=JSON.parse(localStorage.getItem('fivefold-settings')||'null');if(s)Object.assign(settings,s);}catch{}
$('#musicVolume').value=settings.music*100;$('#effectsVolume').value=settings.effects*100;$('#reduced').checked=settings.reduced;$('#quality').value=settings.quality;$('#showStats').checked=settings.stats;audio.setVolumes(settings.music,settings.effects);
function saveSettings(){try{localStorage.setItem('fivefold-settings',JSON.stringify(settings));}catch{}}
function save(){if(game.demo||replay)return;try{localStorage.setItem(SAVE_KEY,campaign.serialize());stored=true;saveError='';$('#saveStatus').textContent='Checkpoint saved on this device.';}catch(e){saveError='Local saving is unavailable. Use Export Save to keep your progress.';$('#saveStatus').textContent=saveError;toast(saveError);}}
function toast(s){if($('#toast').textContent!==s||time>toastUntil){$('#toast').textContent=s;toastUntil=time+3.5;}}
function overlay(id){$$('.overlay').forEach(o=>o.classList.toggle('hidden',o.id!==id));paused=!!id;keyboard.reset();game.pendingActions={};touch.reset();queuedDash=queuedCycle=false;mouseDown=false;if(id==='home')homeSummary();if(id){const focus=$('#'+id+' .primary:not(:disabled)')||$('#'+id+' button:not(:disabled)');focus?.focus({preventScroll:true});}else $('#world').focus({preventScroll:true});}
function homeSummary(){$('#newGame').textContent='NEW GAME';$('#continue').disabled=!stored||!ready;$('#newGame').disabled=!ready;$('#demo').disabled=!ready;$('#worlds').disabled=!ready;$('#saveSummary').textContent=saveError||(!ready?'Loading character…':stored?`Campaign · ${campaign.completed.length}/7 worlds restored · ${levels[campaign.level].name}`:'A new journey awaits.');}
function disposeEnemy(v){v.root.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.dispose();if(o.isMesh){if(!sharedGeo.has(o.geometry))o.geometry.dispose();if(!sharedMat.has(o.material))o.material.dispose();}});scene.remove(v.root);}
function clearEnemies(){for(const v of enemyViews.values())disposeEnemy(v);enemyViews.clear();for(const v of enemyPool)disposeEnemy(v);enemyPool=[];}
function qualityApply(){quality=settings.quality==='auto'?(matchMedia('(pointer:coarse)').matches?'low':'high'):settings.quality;renderer.setPixelRatio(Math.min(devicePixelRatio,quality==='low'?.9:1.35));renderer.shadowMap.enabled=quality!=='low';resize();}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();cinema.resize();}
function start(mode,id=0,tier=1,area='start'){if(!ready)return;audio.start();clearEnemies();world.dispose();fx.reset();mastery.reset();swordTrail.reset();damageNumbers.reset();const demo=mode==='demo';replay=mode==='replay';if(mode==='new'){campaign=new CampaignState();stored=true;}
 let state=replay?CampaignState.parse(campaign.serialize()):demo?new CampaignState():campaign;if(replay){state.level=id;state.snapshot=null;state.unlocked=[0,1,2,3,4];}if(mode==='continue'){id=campaign.level;if(!campaign.snapshot&&campaign.completed.includes(id)&&id<6)id++;}
 const advancing=!demo&&!replay&&id>campaign.level,previousTier=campaign.level+1;game=new CampaignGame(state,{demo,level:id,tier});game.practice=demo&&$('#demoProtect').checked;game.autoCast=demo&&$('#demoAutoCast').checked;game.autoSword=demo&&$('#demoSword').checked;if(demo&&area!=='start'){if(area==='boss'){game.gates.forEach(g=>g.open=true);game.encounters.forEach(e=>e.done=true);game.orbs.forEach(o=>o.collected=true);game.player.z=1080;}else{game.gates.filter(g=>g.z<220).forEach(g=>g.open=true);game.player.z=215;}}
 world=new WorldView(scene,game);const theme=world.theme;sun.color.set(theme.light);ambient.color.set(theme.light);rim.color.set(theme.glow);cameraYaw=0;cameraPitch=.39;cameraDistance=13;heroRoot.position.set(game.player.x,game.player.y,game.player.z);camera.position.set(game.player.x+4,game.player.y+7,game.player.z-12);audio.setTrack(game.level.music);musicCombatUntil=0;running=true;overlay(null);if(!demo&&!replay)save();$('#modeBadge').textContent=demo?`DEMO · TIER ${tier}`:replay?'REPLAY':'';$('#chapter').textContent=`${id+1} · ${game.level.name.toUpperCase()}`;$('#worldTitle').textContent=game.level.name;titleUntil=time+4;toast(game.level.story);renderElements();game.events=[];if(advancing){$('#tierTitle').textContent='All five elements · Tier '+game.tier;$('#tierCopy').textContent=`Base damage rises from ${Math.round(damageScale[previousTier-1]*100)}% to ${Math.round(damageScale[game.tier-1]*100)}%. ${tierFeatures[game.tier-1]} unlocked.`;$('#tierPowers').innerHTML=elements.map((el,i)=>`<div style="--el:${el.color}"><b>${el.glyph}</b><span>${el.name}<strong>${powerNames[i][game.tier-1]}</strong></span></div>`).join('');overlay('tierUp');audio.awaken();}}
function renderElements(){$('#elements').innerHTML=elements.map((el,i)=>`<button data-element="${i}" class="${game.element===i?'selected ':''}${game.canUse(i)?'':'locked'}" style="--el:${el.color}" aria-label="${el.name}${game.canUse(i)?', Tier '+game.tier:', locked'}" title="${powerNames[i][game.tier-1]} · ${Math.round(damageScale[game.tier-1]*100)}% base power" aria-pressed="${game.element===i}"><em>${i+1}</em><b>${el.glyph}</b><small>${game.canUse(i)?el.name.toUpperCase():'LOCKED'}</small><small>${game.canUse(i)?'TIER '+game.tier:'◇'}</small></button>`).join('');$$('[data-element]').forEach(b=>b.onclick=()=>{game.select(+b.dataset.element);renderElements();});}
function selection(mode){selectionMode=mode;$('#selectionTitle').textContent=mode==='demo'?'Elemental demo lab':'The seven worlds';$('#selectionCopy').textContent=mode==='demo'?'Choose any world. The Power tier selector overrides campaign progression for testing. Demo play never changes your campaign save.':'Replay unlocked missions. Your main campaign checkpoint is kept separately.';$('#demoOptions').classList.toggle('hidden',mode!=='demo');$('#levelCards').innerHTML=levels.map(l=>{const open=mode==='demo'||l.id<=campaign.highest;return `<button class="level-card" data-level="${l.id}" ${open?'':'disabled'}><span class="num">0${l.id+1}</span><span><strong>${l.name}</strong><small>${l.boss} · TIER ${l.id+1}</small></span><span class="state">${mode==='demo'?'EXPLORE':campaign.completed.includes(l.id)?'RESTORED':open?'UNLOCKED':'LOCKED'}</span></button>`;}).join('');$$('[data-level]').forEach(b=>b.onclick=()=>start(selectionMode,+b.dataset.level,+$('#demoTier').value,$('#demoArea').value));overlay('selection');}
$('#demoTier').innerHTML=Array.from({length:7},(_,i)=>`<option value="${i+1}">Tier ${i+1}${i===6?' · Mastery':''}</option>`).join('');
function upgradeMenu(from){upgradesReturn=from;const allowed=running&&!game.demo&&!replay&&(game.checkpointReady||game.finished);$('#pointsText').textContent=allowed?`${campaign.points} available · ${campaign.spent}/${campaign.earned} points assigned`:'Visit a checkpoint outside combat to redistribute campaign points.';$('#upgradeRows').innerHTML=elements.map((el,i)=>`<div class="upgrade-row"><strong style="color:${el.color}">${el.glyph} ${el.name}</strong><div>${['impact','control'].map(b=>`<button data-upgrade="${i},${b}" ${!allowed||campaign.points===0||campaign.specializations[i][b]>=3?'disabled':''}>${b.toUpperCase()} <b>${campaign.specializations[i][b]}/3</b> +</button>`).join('')}</div></div>`).join('');$$('[data-upgrade]').forEach(b=>b.onclick=()=>{const [i,branch]=b.dataset.upgrade.split(',');if(campaign.upgrade(+i,branch)){save();upgradeMenu(from);}});$('#refund').disabled=!allowed||!campaign.spent;overlay('upgradePanel');}
function newGameClick(){if(stored&&$('#newGame').textContent==='NEW GAME'){$('#newGame').textContent='START FRESH · REPLACES SAVE';toast('Export your current save in Settings if you want to keep it.');}else start('new');}$('#newGame').onclick=newGameClick;$('#continue').onclick=()=>start('continue');$('#worlds').onclick=()=>selection('replay');$('#demo').onclick=()=>selection('demo');$('#selectionBack').onclick=()=>overlay('home');$('#homeSettings').onclick=()=>overlay('menu');$('#pause').onclick=()=>{if(running&&!paused)overlay('menu');};$('#resume').onclick=()=>{audio.start();if(running)overlay(null);else overlay('home');};$('#toHome').onclick=()=>{if(!game.demo&&!replay)save();running=false;overlay('home');};$('#upgrades').onclick=()=>upgradeMenu('menu');$('#upgradeBack').onclick=()=>overlay(upgradesReturn);$('#refund').onclick=()=>{campaign.refund();save();upgradeMenu(upgradesReturn);};$('#completeUpgrades').onclick=()=>upgradeMenu('complete');$('#completeHome').onclick=()=>{running=false;overlay('home');};$('#claim').onclick=()=>overlay(null);$('#wieldUpgrade').onclick=()=>overlay(null);$('#nextLevel').onclick=()=>{if(game.level.id===6||replay){running=false;overlay('home');}else start(game.demo?'demo':'next',game.level.id+1,game.demo?Math.min(7,game.tier+1):game.level.id+2);};
$('#export').onclick=()=>{const blob=new Blob([campaign.serialize()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='fivefold-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#saveStatus').textContent='Save exported. Import this file on another device to continue.';};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>500000)throw Error('Save file is too large.');const next=CampaignState.parse(await file.text());localStorage.setItem(SAVE_KEY,next.serialize());campaign=next;stored=true;running=false;$('#saveStatus').textContent='Save imported. Choose Continue from the main menu.';}catch(error){$('#saveStatus').textContent='Import failed: '+error.message;}e.target.value='';};
$('#musicVolume').oninput=e=>{settings.music=+e.target.value/100;audio.setVolumes(settings.music,settings.effects);saveSettings();};$('#effectsVolume').oninput=e=>{settings.effects=+e.target.value/100;audio.setVolumes(settings.music,settings.effects);saveSettings();};$('#reduced').onchange=e=>{settings.reduced=e.target.checked;saveSettings();};$('#quality').onchange=e=>{settings.quality=e.target.value;qualityApply();saveSettings();};$('#showStats').onchange=e=>{settings.stats=e.target.checked;saveSettings();};$('#touchEnabled').onchange=e=>touch.setEnabled(e.target.checked);$('#sound').onclick=()=>{audio.setEnabled(!audio.enabled);$('#sound').textContent=audio.enabled?'SOUND ON':'MUTED';};
const musicCredits=[['Asian Drums','Kevin MacLeod','https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1100396'],['Spaghetti Western Theme (Orchestral)','Markus Lindner','https://opengameart.org/content/spaghetti-western-theme-orchestral'],['Machina','Scott Buckley','https://www.scottbuckley.com.au/library/machina/'],['AI Fight','Alexander Ehlers','https://opengameart.org/content/t-t-free-cyberpunk-pack-2'],['Curse of the Scarab','Kevin MacLeod','https://incompetech.com/music/royalty-free/index.html?Search=Search&isrc=USUAN1600014'],['The Long Dark','Scott Buckley','https://www.scottbuckley.com.au/library/the-long-dark/'],['Legionnaire (Original)','Scott Buckley','https://www.scottbuckley.com.au/library/legionnaire/'],['The Old Ones','Scott Buckley','https://www.scottbuckley.com.au/library/the-old-ones/'],['Ascension','Scott Buckley','https://www.scottbuckley.com.au/library/ascension/']];$('#credits').innerHTML=musicCredits.map(([title,by,url])=>`<div><a href="${url}" target="_blank" rel="noopener">${title}</a> — ${by} · ${by==='Alexander Ehlers'?'CC0':title==='Ascension'?'CC BY 3.0':'CC BY 4.0'}</div>`).join('')+'<p>Recordings looped and crossfaded in gameplay. The Long Dark and Ascension: Royalty Free Music by free-stock-music.com. Vanguard character & animations: Adobe Mixamo, via Three.js. Rendering: Three.js, MIT. Environment PBR textures: Poly Haven, CC0 — Rob Tuytel, Dario Barresi and Dimitrios Savva. Original architecture, equipment, elemental art and procedural effects.</p>';
function handleEvents(){const events=game.events.splice(0);for(const e of events){if(e.type==='save')save();if(e.type==='cast'){if(!e.sword){fx.handOrigins=hero.hands();fx.cast(e,time,e.range);audio.cast(e.element,e.ultimate);}else {audio.layer({noise:true,white:true,cutoff:e.combo===3?1500:3000,endCutoff:250,duration:e.combo===3?.32:.19,volume:e.combo===3?.2:.14});if(e.combo===3)audio.layer({noise:true,cutoff:190,endCutoff:65,duration:.26,volume:.12});}}if(e.type==='impact')audio.impact(e.element);if(e.type==='enemyattack')audio.layer({noise:true,cutoff:500,endCutoff:90,duration:.35,volume:.1});mastery.event(e,time);if(e.type==='notice'||e.type==='wave'||e.type==='opened')toast(e.text);if(e.type==='switch')renderElements();if(e.type==='damage')damageNumbers.event(e,time);if(e.type==='unlocked'){audio.awaken();$('#unlockTitle').textContent=elements[e.element].name+' awakens.';$('#unlockCopy').textContent=['Gusts scatter enemies and tear away veils.','Flames consume barricades and leave enemies burning.','Hand arcs call down a devastating storm.','Great waves sweep the field. Water defeats restore vitality.','Stone ruptures break defenses. Earth tempests provide protection.'][e.element];$('#crystalArt').style.setProperty('--el',elements[e.element].color);renderElements();overlay('unlock');}if(e.type==='checkpoint'){audio.awaken();toast('Checkpoint reached · health restored · specializations available');}if(e.type==='mastery'){audio.awaken();toast('Mastery shrine restored.');}if(e.type==='reaction')toast(e.name.toUpperCase()+' · ELEMENTAL REACTION');if(e.type==='boss')toast(e.name+' · Guardian of the fracture');if(e.type==='bossphase')toast(e.name+' · Phase II');if(e.type==='respawn'){fx.reset();mastery.reset();swordTrail.reset();damageNumbers.reset();clearEnemies();world.dispose();world=new WorldView(scene,game);save();toast('Restored at your checkpoint. Earned elements and upgrades are kept.');}if(e.type==='complete'){audio.awaken();$('#completeLabel').textContent=e.final?'THE SEVEN WORLDS RESTORED':'PASSAGE RESTORED';$('#completeTitle').textContent=e.final?'The fracture closes.':game.level.name;$('#completeCopy').textContent=e.final?'The stolen worlds return to their own skies. Your journey is complete. Replay any mission or explore Tier VII in the demo lab.':game.demo?'Guardian defeated. Continue exploring the next world.':replay?'Mission replay complete. Your campaign checkpoint is unchanged.':`The ${game.level.boss} falls. One specialization point earned. All five elements advance to Tier ${Math.min(7,game.tier+1)} in the next world.`;$('#nextLevel').textContent=e.final||replay?'RETURN TO MAIN MENU':'ENTER THE NEXT WORLD';$('#completeUpgrades').disabled=game.demo||replay;overlay('complete');}}
}
function enemyVisual(e){let v=enemyViews.get(e.id);if(v)return v;v=hero.makeEnemy(e.role==='boss'?10:e.id,game.level.theme,e.role);v.root.scale.setScalar(e.role==='boss'?1.75:1);scene.add(v.root);enemyViews.set(e.id,v);return v;}
function drawEnemies(){const p=game.player;for(const e of game.enemies){if(!e.active||Math.abs(e.z-p.z)>65)continue;if(e.hp<=0){const v=enemyViews.get(e.id);if(v){v.deathTime??=time;v.root.rotation.x=Math.min(1.5,(time-v.deathTime)*3);v.root.position.y=-(time-v.deathTime)*.6;if(time-v.deathTime>1.4){disposeEnemy(v);enemyViews.delete(e.id);}}continue;}const v=enemyVisual(e);v.root.visible=true;const moving=v.lastX!==undefined&&Math.hypot(e.x-v.lastX,e.z-v.lastZ)>.005;v.root.position.set(e.x,game.walkHeight(e.x,e.z),e.z);v.root.rotation.set(0,Math.atan2(p.x-e.x,p.z-e.z),0);v.update(time,moving);v.lastX=e.x;v.lastZ=e.z;}for(const [id,v]of enemyViews){const e=game.enemies.find(e=>e.id===id);if(!e||Math.abs(e.z-p.z)>70){disposeEnemy(v);enemyViews.delete(id);}}}
function drawWarnings(){for(let i=0;i<warnings.length;i++){const mesh=warnings[i],t=game.telegraphs[i];mesh.visible=!!t;if(!t)continue;mesh.position.set(t.x,game.walkHeight(t.x,t.z)+.065,t.z);mesh.rotation.y=0;const progress=1-t.life/t.max;if(t.kind==='fan'||t.kind==='beam'){mesh.rotation.y=Math.atan2(t.dx,t.dz);mesh.children[0].visible=false;mesh.children[1].geometry=t.kind==='fan'?warningFan:warningBeam;mesh.children[1].position.set(0,0,t.kind==='fan'?0:16);mesh.scale.set(1,1,1);}else{mesh.children[0].visible=true;mesh.children[1].geometry=warningCircle;mesh.children.forEach(m=>m.position.set(0,0,0));mesh.scale.setScalar(t.kind==='melee'?2.2:t.r);}mesh.children[1].material.opacity=.06+progress*.16;}}
function hud(){const p=game.player;$('#powerGrowth').textContent=game.canUse(game.element)?`${powerNames[game.element][game.tier-1]} · TIER ${game.tier} · ${Math.round(damageScale[game.tier-1]*(1+game.specs[game.element].impact*.15)*100)}% POWER`:'FIND AN ELEMENTAL CRYSTAL';$('#healthFill').style.width=Math.max(0,p.hp)+'%';$('#healthText').textContent=`${Math.ceil(p.hp)} / 100${game.shield>0?' · STONE GUARD':''}`;$('#checkpointText').textContent=game.checkpointReady?'CHECKPOINT · UPGRADES READY':'';$('#progress').style.width=game.progress*100+'%';let goal;if(game.currentOrb&&game.currentOrb.z<=((game.currentGate?.z)||Infinity))goal=`Find the ${elements[game.currentOrb.type].name} crystal · ${Math.ceil(dist(p,game.currentOrb))} m`;else if(game.inCombat)goal=game.boss.active&&game.boss.hp>0?(game.relays.some(r=>r.hp>0)?'Destroy the relay pylons.':'Defeat the '+game.boss.name+'.'):'Defeat the district guards. Prioritize support units.';else if(game.currentGate)goal=game.currentGate.label+' · '+elements[game.currentGate.type].name;else goal='Reach the guardian court.';$('#objectiveText').textContent=goal;const enc=game.encounters.find(e=>e.started&&!e.done);$('#stage').textContent=enc?`ENCOUNTER ${enc.id+1} · WAVE ${enc.wave}/${game.level.waves}`:`WORLD ${game.level.id+1} · TIER ${game.tier}`;
const boss=game.boss;$('#bossHud').classList.toggle('hidden',!boss.active||boss.hp<=0);$('#bossName').textContent=boss.name;$('#bossPhase').textContent=`GUARDIAN · PHASE ${boss.phase} / II`;$('#bossFill').style.width=Math.max(0,boss.hp/boss.max*100)+'%';$('#staggerFill').style.width=boss.stagger+'%';const target=game.acquireTarget({x:p.dx,z:p.dz});let shown=false;if(target){const point=new T.Vector3(target.x,game.walkHeight(target.x,target.z)+(target.role==='boss'?5:3.6),target.z).project(camera);if(point.z<1&&point.z>-1&&Math.abs(point.x)<1&&Math.abs(point.y)<1){shown=true;$('#targetLock').style.left=(point.x*.5+.5)*innerWidth+'px';$('#targetLock').style.top=(-point.y*.5+.5)*innerHeight+'px';$('#targetName').textContent=target.kind==='gate'?elements[target.type].name.toUpperCase():target.kind==='relay'?'RELAY':target.role.toUpperCase();$('#targetFill').style.width=target.hp/target.max*100+'%';}}$('#targetLock').classList.toggle('hidden',!shown||paused);
}
const keyboard=new KeyboardControls({keys,isPlaying:()=>running&&!paused,onGesture:()=>audio.start(),onAction:code=>{
 if(/^(Digit|Numpad)[1-5]$/.test(code)){game.select(+code.slice(-1)-1);renderElements();}
 if(code==='ShiftLeft'||code==='ShiftRight')queuedDash=true;
 if(code==='Tab')queuedCycle=true;
 if(code==='KeyM')$('#sound').click();
 if(code==='KeyR'){cameraYaw=0;cameraPitch=.39;cameraDistance=13;}
},onEscape:()=>{
 if(!paused){if(running)overlay('menu');return;}
 const active=$('.overlay:not(.hidden)')?.id;
 if(active==='menu'){audio.start();overlay(running?null:'home');}
 else if(active==='selection')overlay('home');
 else if(active==='upgradePanel')overlay(upgradesReturn);
 else if(active==='unlock'||active==='tierUp')overlay(null);
},onSuspend:()=>{mouseDown=false;touch.reset();queuedDash=queuedCycle=false;if(running&&!paused)overlay('menu');}});
window.addEventListener('resize',resize);$('#world').addEventListener('contextmenu',e=>e.preventDefault());$('#world').addEventListener('pointerdown',e=>{if(e.button===2){mouseDown=true;$('#world').setPointerCapture(e.pointerId);}});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('#world').addEventListener(event,()=>mouseDown=false);$('#world').addEventListener('pointermove',e=>{if(mouseDown&&!paused){cameraYaw-=e.movementX*.006;cameraPitch=clamp(cameraPitch+e.movementY*.003,.15,.95);}});$('#world').addEventListener('wheel',e=>{cameraDistance=clamp(cameraDistance+e.deltaY*.008,7,22);e.preventDefault();},{passive:false});
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.1,(now-last)/1000);last=now;time+=dt;frameCount++;frameTotal+=dt;const p=game.player;if(running&&!paused){if(keys.has('KeyQ'))cameraYaw+=dt*1.5;if(keys.has('KeyF'))cameraYaw-=dt*1.5;const axes=keyboard.axes(),move=cameraMovement(axes.x+touch.x,axes.z+touch.y,cameraYaw),c=Math.cos(cameraYaw),s=Math.sin(cameraYaw);if(game.demo&&game.practice)game.player.invincible=1;game.advance(dt,{view:{x:camera.position.x,z:camera.position.z,dx:s,dz:c,tan:Math.tan(camera.fov*Math.PI/360)*camera.aspect},mx:move.mx,mz:move.mz,cast:keyboard.takePress('Space')||keys.has('Space')||touch.casting||game.autoCast,tempest:keyboard.takePress('KeyE')||keys.has('KeyE')||touch.tempest,sword:keyboard.takePress('KeyC')||keys.has('KeyC')||touch.sword||game.autoSword,dash:queuedDash,cycle:queuedCycle});queuedDash=queuedCycle=false;handleEvents();}
heroRoot.position.set(game.player.x,game.player.y,game.player.z);heroRoot.rotation.y=Math.atan2(game.player.dx,game.player.dz);hero.update(time,{...game.player,swordAnim:game.swordAnim,swordDuration:game.swordDuration,combo:game.combo,moving:paused?0:game.player.moving},!paused&&game.castAnim>0,game.element);const swordPose=SwordMotion.pose(game.combo||1,1-game.swordAnim/(game.swordDuration||.34));swordTrail.update(time,ready?hero.swordSegment():null,!paused&&game.swordAnim>0&&swordPose.trail,game.element,game.combo,settings.reduced);fx.handOrigins=hero.hands();fx.update(time,settings.reduced||quality==='low');mastery.update(time,game,settings.reduced);if(ready)drawEnemies();drawWarnings();world.update(time,quality);
const framedDistance=cameraDistance+(!paused&&game.castAnim>0&&game.element===3?4:0);const aim=new T.Vector3(game.player.x,game.player.y+2.3,game.player.z),desired=aim.clone().add(new T.Vector3(-Math.sin(cameraYaw)*Math.cos(cameraPitch)*framedDistance,Math.sin(cameraPitch)*framedDistance,-Math.cos(cameraYaw)*Math.cos(cameraPitch)*framedDistance));const collision=world.cameraPosition(aim,desired);camera.position.lerp(collision,1-Math.exp(-dt*10));camera.lookAt(aim.clone().add(new T.Vector3(Math.sin(cameraYaw)*5,1.1,Math.cos(cameraYaw)*5)));sun.position.set(p.x-25,42,p.z-15);sun.target.position.set(p.x,0,p.z+12);rim.position.set(p.x+12,10,p.z+18);rim.target.position.set(p.x,1,p.z);
damageNumbers.update(time,camera,innerWidth,innerHeight,paused,settings.reduced);if(game.inCombat)musicCombatUntil=time+5;const combat=time<musicCombatUntil;audio.setTrack(combat?game.level.combat:game.level.music);audio.tickMusic(running&&!paused,combat,game.level.theme);renderer.info.reset();if(quality==='low'){renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;renderer.render(scene,camera);}else{renderer.toneMapping=T.NoToneMapping;cinema.render(time,settings.reduced,0);}if(time-uiTime>.12){uiTime=time;hud();}$('#toast').classList.toggle('show',time<toastUntil);$('#worldTitle').classList.toggle('show',running&&!paused&&time<titleUntil);$('#stats').classList.toggle('hidden',!settings.stats);if(time-statsTime>1){fps=frameCount/frameTotal;frameCount=0;frameTotal=0;statsTime=time;if(settings.quality==='auto'&&running&&!paused&&fps<42&&quality==='high'){autoSamples++;if(autoSamples>4){quality='low';renderer.setPixelRatio(.9);renderer.shadowMap.enabled=false;resize();toast('Graphics adjusted for smoother play.');}}$('#stats').textContent=`${fps.toFixed(1)} FPS · ${quality} · ${innerWidth}×${innerHeight}\n${renderer.info.render.calls} draws · ${(renderer.info.render.triangles/1000).toFixed(0)}k triangles\nGPU: ${renderer.info.memory.geometries} geometries / ${renderer.info.memory.textures} textures\nFX: ${fx.jobs.length} jobs / ${mastery.jobs.length} accents\nAudio: ${audio.voices} voices / ${audio.decks.length} streams${audio.musicError?'\n'+audio.musicError:''}\n${adapter}`;}}
qualityApply();renderElements();homeSummary();hero.ready.then(()=>{ready=true;hero.root.traverse(o=>{if(o.isMesh){sharedGeo.add(o.geometry);sharedMat.add(o.material);}});homeSummary();}).catch(e=>{$('#saveSummary').textContent='Character loading failed. Check that the complete game folder was downloaded.';console.error(e);});requestAnimationFrame(frame);
})();
