/* Bounded accents for persistent fields, reactions, sword trails and Tier VII mastery forms. */
(()=>{const T=THREE,C=['#cce9dd','#ff9b35','#b579ff','#7bbacf','#c2a77b'];
class MasteryFX{
 constructor(scene){this.root=new T.Group();scene.add(this.root);this.rings=[];this.jobs=[];this.materials=[];this.geometries=[];this.dummy=new T.Object3D();
  const geo=new T.IcosahedronGeometry(.16,0);this.geometries.push(geo);const mat=new T.MeshBasicMaterial({color:'#ffffff',transparent:true,opacity:.8});this.materials.push(mat);this.particles=new T.InstancedMesh(geo,mat,240);this.particles.instanceMatrix.setUsage(T.DynamicDrawUsage);this.particles.frustumCulled=false;this.root.add(this.particles);this.particles.count=0;
  const ringGeo=new T.RingGeometry(.93,1,64);this.geometries.push(ringGeo);for(let i=0;i<36;i++){const m=new T.MeshBasicMaterial({color:C[0],transparent:true,opacity:.4,side:T.DoubleSide,depthWrite:false});this.materials.push(m);const r=new T.Mesh(ringGeo,m);r.rotation.x=-Math.PI/2;this.root.add(r);this.rings.push(r);}
  this.phoenix=new T.Group();this.root.add(this.phoenix);const shape=new T.Shape();shape.moveTo(0,0);shape.bezierCurveTo(2,5,6,6,10,8);shape.lineTo(8,3);shape.lineTo(5,2.3);shape.lineTo(7,1.6);shape.lineTo(3,.7);shape.closePath();const wingGeo=new T.ShapeGeometry(shape,18);this.geometries.push(wingGeo);for(const side of [-1,1]){const mat=new T.MeshBasicMaterial({color:'#ffc270',side:T.DoubleSide,transparent:true,opacity:.7,depthWrite:false});this.materials.push(mat);const m=new T.Mesh(wingGeo,mat);m.scale.x=side;this.phoenix.add(m);}this.phoenix.visible=false;
  this.cyclone=new T.Group();this.root.add(this.cyclone);for(let i=0;i<9;i++){const geo=new T.TorusGeometry(1,.025,4,64,5.4),mat=new T.MeshBasicMaterial({color:'#d7ece3',transparent:true,opacity:.65});this.geometries.push(geo);this.materials.push(mat);const m=new T.Mesh(geo,mat);m.rotation.x=Math.PI/2;m.position.y=i*1.2;this.cyclone.add(m);}this.cyclone.visible=false;
  this.bastion=new T.Group();this.root.add(this.bastion);for(let i=0;i<7;i++){const geo=new T.DodecahedronGeometry(1,0),mat=new T.MeshStandardMaterial({color:'#a19580',roughness:.7,metalness:.15});this.geometries.push(geo);this.materials.push(mat);const m=new T.Mesh(geo,mat);const a=i/7*6.283;m.position.set(Math.sin(a)*3,1,Math.cos(a)*3);m.scale.set(.5,1.7,.5);this.bastion.add(m);}this.bastion.visible=false;
 }
 event(e,time){if(e.type==='reaction'||e.type==='opened'||e.type==='defeat'||e.type==='sword'||e.type==='chain')this.jobs.push({...e,x:e.x+(e.type==='sword'?(e.dx||0)*2:0),z:e.z+(e.type==='sword'?(e.dz||0)*2:0),birth:time+(e.type==='sword'?(e.combo===3?.2:.08):0)});if(this.jobs.length>24)this.jobs.shift();}
 update(time,game,gentle){this.jobs=this.jobs.filter(j=>time-j.birth<.9);let ring=0,particle=0;for(const f of game.fields){const r=this.rings[ring++];if(!r)break;r.visible=true;r.material.color.set(C[f.element]);r.material.opacity=.11*Math.min(1,f.life*2);r.position.set(f.x,game.walkHeight(f.x,f.z)+.05,f.z);r.scale.setScalar(f.r);r.rotation.z=time*(f.element===3?-1:1);}
  for(const job of this.jobs){const age=time-job.birth;if(age<0)continue;if(ring<this.rings.length){const r=this.rings[ring++];r.visible=true;r.material.color.set(C[job.element||0]);r.material.opacity=(1-age/.9)*.5;r.position.set(job.x,game.walkHeight(job.x,job.z)+.1,job.z);r.scale.setScalar(.5+age*(job.type==='reaction'||job.combo===3?10:4));}for(let i=0;i<(gentle?4:10)&&particle<240;i++){const a=i*2.4,rad=age*6;this.dummy.position.set(job.x+Math.sin(a)*rad,1+Math.sin(age*3.5)*(1+i*.1),job.z+Math.cos(a)*rad);this.dummy.rotation.set(age*4,a,time);this.dummy.scale.setScalar(1-age);if(job.type==='sword'){this.dummy.scale.set(.16*(1-age),.12*(1-age),1.7*(1-age));}this.dummy.updateMatrix();this.particles.setMatrixAt(particle,this.dummy.matrix);this.particles.setColorAt(particle++,new T.Color(C[job.element||0]));}}
  for(;ring<this.rings.length;ring++)this.rings[ring].visible=false;this.particles.count=particle;this.particles.instanceMatrix.needsUpdate=true;if(this.particles.instanceColor)this.particles.instanceColor.needsUpdate=true;
  const p=game.player,active=game.tier===7&&game.castAnim>0;this.phoenix.visible=active&&game.element===1;this.phoenix.position.set(p.x+p.dx*13,2+p.y,p.z+p.dz*13);this.phoenix.rotation.y=Math.atan2(p.dx,p.dz);this.phoenix.scale.setScalar(.7);for(let i=0;i<2;i++)this.phoenix.children[i].rotation.y=Math.sin(time*7)*.2*(i?1:-1);
  this.cyclone.visible=active&&game.element===0;this.cyclone.position.set(p.x+p.dx*17,p.y,p.z+p.dz*17);this.cyclone.children.forEach((m,i)=>{m.scale.setScalar(2+i*.48);m.rotation.z=time*4+i;});
  this.bastion.visible=game.shield>0;this.bastion.children.forEach((m,i)=>m.visible=i<2+game.tier);this.bastion.position.set(p.x,p.y,p.z);this.bastion.rotation.y=time*.3;
 }
 reset(){this.jobs=[];this.particles.count=0;this.rings.forEach(r=>r.visible=false);this.phoenix.visible=this.cyclone.visible=this.bastion.visible=false;}
}
window.MasteryFX=MasteryFX;})();
