/* Authored environmental composition plus bounded reactive scenery. */
(()=>{'use strict';const T=THREE,C=['#d4eadd','#ff9145','#ba8aff','#86d7dc','#d1b284'];
class WorldDetail{
 constructor(world,game){this.world=world;this.game=game;this.root=new T.Group();world.root.add(this.root);this.resources=[];this.flags=[];this.time=0;this.wind=0;this.marks=[];this.flash=0;this.dummy=new T.Object3D();const w=world,g=game,z=g.signature.z,x=g.level.centerAt(z);
  this.mat=(color,extra={})=>{const m=new T.MeshStandardMaterial({color,roughness:.7,...extra});this.resources.push(m);return m;};
  this.mesh=(geo,mat,parent=this.root)=>{this.resources.push(geo);const m=new T.Mesh(geo,mat);m.castShadow=m.receiveShadow=true;parent.add(m);return m;};
  const stone=this.mat('#777570'),iron=this.mat('#273239',{metalness:.7,roughness:.35}),warm=this.mat('#f7b76f',{emissive:'#d28b3b',emissiveIntensity:1.4}),wood=this.mat('#342d2c');
  // Fine architectural detail is merged with the existing material batches.
  for(let base=25;base<g.level.length-20;base+=44){const cx=g.level.centerAt(base);w.begin(base);for(const side of [-1,1]){const edge=cx+side*19;w.box('stone',edge,.22,base,1.3,.44,7);for(let j=0;j<3;j++){w.box('wood',edge,1.4,base+j*2,.12,2.8,.12);w.box('metal',edge,2.75,base+j*2,.55,.18,.7);}if(g.level.theme==='japan'||g.level.theme==='gothic'){for(let k=0;k<5;k++)w.box('wood',cx+side*22,1.1+k*.3,base, .15,.06,3);w.box('metal',cx+side*21.8,3.3,base,2,.12,4,0,0,side*.13);}if(g.level.theme==='west'){w.box('wood',edge,1.5,base, .1,2.7,3);w.box('accent',edge,2.8,base,.2,.5,3.4);}}w.end();}
  const poolGeo=new T.PlaneGeometry(36,48,24,24);const water=new T.ShaderMaterial({transparent:true,depthWrite:false,side:T.DoubleSide,uniforms:{time:{value:0},amount:{value:.2}},vertexShader:'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 v;uniform float time,amount;void main(){float a=sin(v.x*140.+sin(v.y*28.+time)*2.+time*2.);float b=pow(max(0.,sin(v.y*85.-time*3.+sin(v.x*24.))),18.);vec3 c=mix(vec3(.035,.095,.12),vec3(.32,.55,.56),b*.6+abs(a)*.08);gl_FragColor=vec4(c,amount);}' });this.resources.push(water);this.water=this.mesh(poolGeo,water);this.water.rotation.x=-Math.PI/2;this.water.position.set(x,g.showcase?.255:.075,z);this.water.receiveShadow=false;
  this.marker=this.mesh(new T.TorusGeometry(2,.035,5,60),new T.MeshBasicMaterial({color:C[g.level.signature?.element??3],transparent:true,opacity:.65}));this.resources.push(this.marker.material);this.marker.rotation.x=Math.PI/2;this.marker.position.set(x-8,.15,z);
  this.beam=this.mesh(new T.PlaneGeometry(4.4,50),new T.MeshBasicMaterial({color:'#ffb75c',transparent:true,opacity:.2,side:T.DoubleSide,depthWrite:false}));this.resources.push(this.beam.material);this.beam.rotation.x=-Math.PI/2;this.beam.position.set(x,.11,z);
  this.structure=new T.Group();this.root.add(this.structure);this.structure.position.set(x,0,z);
  const piece=(geo,mat,px,py,pz,sx=1,sy=1,sz=1)=>{const m=this.mesh(geo,mat,this.structure);m.position.set(px,py,pz);m.scale.set(sx,sy,sz);return m;};
  switch(g.level.id){
   case 0:for(const side of [-1,1]){piece(new T.CylinderGeometry(.4,.65,3,8),stone,side*14,1.5,0);piece(new T.CylinderGeometry(.9,1,.6,8),warm,side*14,3.4,0);piece(new T.ConeGeometry(1.5,.6,4),iron,side*14,4,0);piece(new T.TorusGeometry(2,.09,6,32,Math.PI),wood,side*15,2,12);}break;
   case 1:this.rail=new T.Group();this.structure.add(this.rail);for(let i=0;i<10;i++){const m=this.mesh(new T.BoxGeometry(.2,3.5,6),wood,this.rail);m.position.set(-3+i*.65,2,0);}for(const side of [-1,1])for(const end of [-1,1]){const m=this.mesh(new T.CylinderGeometry(.65,.65,.2,12),iron,this.rail);m.rotation.z=Math.PI/2;m.position.set(side*3,.65,end*2);}break;
   case 2:for(const side of [-1,1]){piece(new T.CylinderGeometry(1.3,1.3,6,12),iron,side*13,3,0);piece(new T.TorusGeometry(1.5,.1,5,32),warm,side*13,5,0).rotation.x=Math.PI/2;}break;
   case 3:this.sunShield=piece(new T.BoxGeometry(7,5,2.4),stone,0,-3,-5);for(let i=-1;i<=1;i++){piece(new T.CylinderGeometry(1.1,1.3,9,12),stone,i*12,4.5,18);piece(new T.TorusGeometry(2,.3,6,24),warm,i*12,10,18);}break;
   case 4:this.iceSeal=piece(new T.BoxGeometry(8,5,.5),this.mat('#a2ccdc',{transparent:true,opacity:.6}),0,2.5,0);piece(new T.BoxGeometry(12,.7,15),wood,0,6,3);for(const side of [-1,1]){piece(new T.ConeGeometry(3,8,5),stone,side*14,4,3);piece(new T.ConeGeometry(2,6,5),iron,side*15,2,11);}break;
   case 5:for(const side of [-1,1]){piece(new T.CylinderGeometry(2,2.6,7,16),iron,side*12,3.5,0);piece(new T.TorusGeometry(2.1,.2,6,32),warm,side*12,2,0).rotation.x=Math.PI/2;for(let j=0;j<4;j++)piece(new T.CylinderGeometry(.25,.25,10,8),iron,side*12+j*.7,6,4);}break;
   case 6:for(let i=0;i<7;i++){const a=i/7*Math.PI*2;piece(new T.DodecahedronGeometry(1,0),stone,Math.sin(a)*15,4+i%3,Math.cos(a)*18,2,4,2);}break;
  }
  const leafGeo=new T.PlaneGeometry(.25,.5),leafMat=new T.MeshBasicMaterial({color:g.level.id===0?'#b66944':'#a49b87',side:T.DoubleSide});this.resources.push(leafGeo,leafMat);this.debris=new T.InstancedMesh(leafGeo,leafMat,160);this.debris.instanceMatrix.setUsage(T.DynamicDrawUsage);this.debris.frustumCulled=false;this.root.add(this.debris);
  const markGeo=new T.CircleGeometry(1,16),markMat=new T.MeshBasicMaterial({color:'#211c1b',transparent:true,opacity:.48,depthWrite:false});this.resources.push(markGeo,markMat);this.scorch=new T.InstancedMesh(markGeo,markMat,32);this.scorch.instanceMatrix.setUsage(T.DynamicDrawUsage);this.scorch.frustumCulled=false;this.root.add(this.scorch);this.scorch.count=0;
  const coverGeo=new T.DodecahedronGeometry(1,0),coverMat=this.mat('#898477');this.resources.push(coverGeo);this.cover=new T.InstancedMesh(coverGeo,coverMat,12);this.cover.frustumCulled=false;this.root.add(this.cover);this.cover.count=0;
  this.light=new T.PointLight('#bd9cff',0,40,2);this.root.add(this.light);
  const flagMat=this.mat('#413334',{side:T.DoubleSide});for(let i=0;i<12;i++){const zz=20+i*(g.level.length-40)/12,xx=g.level.centerAt(zz)+(i%2?18:-18),m=this.mesh(new T.PlaneGeometry(1.5,3,6,12),flagMat);m.position.set(xx,4,zz);this.flags.push(m);}
  this.links=[];for(const relay of g.relays){const geo=new T.BufferGeometry().setFromPoints([new T.Vector3(relay.x,3,relay.z),new T.Vector3(g.boss.x,4,g.boss.z)]),mat=new T.LineBasicMaterial({color:'#aa83ff',transparent:true,opacity:.6});this.resources.push(geo,mat);const line=new T.Line(geo,mat);this.root.add(line);this.links.push({line,relay});}
 }
 event(e,time){if(e.type==='cast'&&!e.sword){if(e.element===0||e.element===3)this.wind=1;if(e.element===2){this.flash=1;this.light.position.set(e.impactX||e.x,7,e.impactZ||e.z);}if(e.element===1||e.element===4){this.marks.push({x:e.impactX??e.x,z:e.impactZ??e.z,birth:time,earth:e.element===4});if(this.marks.length>32)this.marks.shift();}}}
 update(time,quality){const g=this.game,s=g.signature,p=g.player,dt=Math.min(.1,time-this.time);this.time=time;this.wind=Math.max(0,this.wind-dt);this.flash=Math.max(0,this.flash-dt*5);this.light.intensity=quality==='low'?0:this.flash*18;this.water.material.uniforms.time.value=time;this.water.visible=g.level.id===0||g.showcase;this.water.material.uniforms.amount.value=s.done?.8:.2;this.marker.visible=!s.done&&Math.abs(p.z-s.z)<40;this.marker.rotation.z=time*.3;this.beam.visible=s.hazard;this.beam.position.set(s.beamX,.11,s.hazardZ??s.z);if(this.sunShield)this.sunShield.position.y=s.done?2.5:-3;if(this.iceSeal)this.iceSeal.visible=!s.done;this.beam.material.opacity=s.cycle<1.5?.14+s.cycle*.12:s.cycle<1.8?.7:.06;if(this.rail)this.rail.position.set((s.rail?.x??g.level.centerAt(s.z))-g.level.centerAt(s.z),0,9);
  if(this.restored){if(this.world.sky?.material.uniforms.restored)this.world.sky.material.uniforms.restored.value=Math.min(1,this.world.sky.material.uniforms.restored.value+dt*.5);this.world.weather.material.opacity=Math.max(.02,this.world.weather.material.opacity-dt*.08);}if(g.level.id===6&&g.boss.active){this.water.visible=s.phase===0;this.water.position.set(g.boss.x,.1,g.boss.z-8);this.water.material.uniforms.amount.value=.5;}
  this.links.forEach(({line,relay})=>line.visible=relay.hp>0&&g.boss.active);
  for(const m of this.flags){const a=m.geometry.attributes.position;for(let i=0;i<a.count;i++){const y=a.getY(i),u=(1.5-y)/3;a.setZ(i,Math.sin(time*(2+this.wind*5)+m.position.z+u*3)*u*(.12+this.wind*.45));}a.needsUpdate=true;}
  const count=quality==='low'?64:160;this.debris.count=count;for(let i=0;i<count;i++){const a=i*2.399,t=time*(.15+this.wind*.8),x=p.x+Math.sin(a+t)*(5+i%18),z=p.z+(i%31-15)*1.7,y=.15+((i*.41+time*.3)%(this.wind?7:2));this.dummy.position.set(x,y,z);this.dummy.rotation.set(a+time*.5,a,t+i);this.dummy.scale.setScalar(1);this.dummy.updateMatrix();this.debris.setMatrixAt(i,this.dummy.matrix);}this.debris.instanceMatrix.needsUpdate=true;
  this.marks=this.marks.filter(m=>time-m.birth<12);this.scorch.count=this.marks.length;this.marks.forEach((m,i)=>{this.dummy.position.set(m.x,g.walkHeight(m.x,m.z)+.08,m.z);this.dummy.rotation.set(-Math.PI/2,0,i);this.dummy.scale.set(2.4,1.4,1);this.dummy.updateMatrix();this.scorch.setMatrixAt(i,this.dummy.matrix);});this.scorch.instanceMatrix.needsUpdate=true;
  this.cover.count=0;for(const c of g.covers)for(let i=0;i<6;i++){const u=(i-2.5)*1.1;this.dummy.position.set(c.x+c.dz*u,Math.min(1,c.life*3)*1.4,c.z-c.dx*u);this.dummy.rotation.set(.1,i*.8,.15);this.dummy.scale.set(.7,1.8,.65);this.dummy.updateMatrix();this.cover.setMatrixAt(this.cover.count++,this.dummy.matrix);}this.cover.instanceMatrix.needsUpdate=true;
 }
 dispose(){this.root.removeFromParent();for(const r of new Set(this.resources))r.dispose();this.root.clear();}
}
window.WorldDetail=WorldDetail;
})();
