/* Authored architecture assembled into material batches. Only nearby districts are rendered. */
(()=>{'use strict';const T=THREE,TAU=Math.PI*2;
const themes={
 japan:{sky:'#293b48',fog:'#566775',ground:'#6c7070',stone:'#515b60',wood:'#372c28',metal:'#272d34',glow:'#e2ac6c',accent:'#753d35',light:'#c3d0d8'},
 west:{sky:'#67554f',fog:'#aa8b6b',ground:'#a38c6c',stone:'#806451',wood:'#584338',metal:'#343539',glow:'#ffcc87',accent:'#884e3c',light:'#ffd4a1'},
 cyber:{sky:'#101522',fog:'#1f3345',ground:'#414c57',stone:'#313b4a',wood:'#242938',metal:'#172631',glow:'#3bd6ee',accent:'#d73888',light:'#9bcada'},
 egypt:{sky:'#6e635a',fog:'#b9a17d',ground:'#b39b75',stone:'#9d8158',wood:'#685137',metal:'#4e564f',glow:'#ffd08a',accent:'#47737a',light:'#ffe2b3'},
 ice:{sky:'#182d41',fog:'#637e93',ground:'#a9bbc5',stone:'#596f7e',wood:'#3c464f',metal:'#303e4a',glow:'#8bf3da',accent:'#486889',light:'#cae5ff'},
 gothic:{sky:'#292732',fog:'#62585d',ground:'#696266',stone:'#4d484e',wood:'#393035',metal:'#272a30',glow:'#ff9a48',accent:'#833b30',light:'#cebcb8'},
 celestial:{sky:'#192735',fog:'#465967',ground:'#434c55',stone:'#8d8980',wood:'#453e38',metal:'#26343e',glow:'#edca85',accent:'#b69855',light:'#c7dae1'}
};
const rand=n=>{let v=Math.sin(n*127.1+31.7)*43758.545;return v-Math.floor(v);};
class WorldView{
 constructor(scene,game){this.scene=scene;this.game=game;this.theme=themes[game.level.theme];this.root=new T.Group();scene.add(this.root);this.chunks=[];this.materials=new Map();this.geo=new Set();this.textures=[];this.colliders=[];this.dynamic=[];this.orbs=[];this.gates=[];this.relays=[];this.barrels=[];this.themeName=game.level.theme;this.makeTexture();this.loadPBR();this.build();this.detail=new WorldDetail(this,game);if(game.showcase&&window.buildShowcase)window.buildShowcase(this,game);}
 makeTexture(){const c=document.createElement('canvas');c.width=c.height=512;const x=c.getContext('2d');x.fillStyle='#85817a';x.fillRect(0,0,512,512);for(let row=0;row<16;row++)for(let col=0;col<9;col++){const v=90+rand(row*19+col)*50;x.fillStyle=`rgb(${v},${v},${v})`;x.fillRect(col*64-(row%2)*32+2,row*32+2,61,29);x.strokeStyle='#2a2b2e';x.lineWidth=.8;x.strokeRect(col*64-(row%2)*32+2,row*32+2,61,29);}const img=x.getImageData(0,0,512,512);for(let i=0;i<img.data.length;i+=4){const v=(rand(i)-.5)*35;for(let k=0;k<3;k++)img.data[i+k]+=v;}x.putImageData(img,0,0);this.texture=new T.CanvasTexture(c);this.texture.wrapS=this.texture.wrapT=T.RepeatWrapping;this.texture.colorSpace=T.SRGBColorSpace;this.textures.push(this.texture);const wood=document.createElement('canvas');wood.width=wood.height=256;const w=wood.getContext('2d');w.fillStyle='#86796c';w.fillRect(0,0,256,256);for(let i=0;i<1500;i++){w.strokeStyle=i%3?'#4d423630':'#c8ae8b44';w.lineWidth=.3+rand(i)*1.4;const x=rand(i)*256,y=rand(i+3)*256;w.beginPath();w.moveTo(x,y);w.bezierCurveTo(x+2,y+5,x-2,y+20,x+rand(i+5)*3,y+60);w.stroke();}this.woodTexture=new T.CanvasTexture(wood);this.woodTexture.wrapS=this.woodTexture.wrapT=T.RepeatWrapping;this.woodTexture.colorSpace=T.SRGBColorSpace;this.textures.push(this.woodTexture);}
 loadPBR(){const loader=new T.TextureLoader();this.pbr={};const kinds=['stone','wood',...(this.themeName==='west'?['dirt']:this.themeName==='egypt'?['sand']:[])];for(const kind of kinds){const maps={};for(const [name,slot]of [['color','map'],['normal','normalMap'],['rough','roughnessMap']]){const texture=loader.load('assets/textures/'+kind+'-'+name+'.jpg');texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.anisotropy=4;if(name==='color')texture.colorSpace=T.SRGBColorSpace;this.textures.push(texture);maps[slot]=texture;}this.pbr[kind]=maps;}}
 mat(key){if(this.materials.has(key))return this.materials.get(key);let m;const color=this.theme[key]||key;if(key==='glow')m=new T.MeshStandardMaterial({color,emissive:color,emissiveIntensity:2.5,roughness:.3});else{const surface=key==='wood'?'wood':key==='ground'?this.themeName==='west'?'dirt':this.themeName==='egypt'?'sand':'stone':key==='stone'?'stone':null;m=new T.MeshStandardMaterial({color,roughness:key==='metal'?.45:.85,metalness:key==='metal'?.7:.05,...(surface?this.pbr[surface]:{}),normalScale:new T.Vector2(.7,.7)});if(surface)m.color.lerp(new T.Color('#d4d5d4'),.48);}this.materials.set(key,m);return m;}

 geometry(g){this.geo.add(g);return g;}
 mesh(g,mat,parent=this.root){const m=new T.Mesh(this.geometry(g),typeof mat==='string'?this.mat(mat):mat);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
 begin(z){this.batch=new Map();this.chunk=new T.Group();this.chunk.userData.z=z;this.root.add(this.chunk);this.chunks.push(this.chunk);}
 add(g,key,x,y,z,sx=1,sy=1,sz=1,rx=0,ry=0,rz=0){const o=new T.Object3D();o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.rotation.set(rx,ry,rz);o.updateMatrix();const b=g.index?g.toNonIndexed():g.clone();b.applyMatrix4(o.matrix);if(['ground','stone','wood'].includes(key)){const p=b.attributes.position,n=b.attributes.normal,uv=b.attributes.uv;for(let i=0;i<p.count;i++){const nx=Math.abs(n.getX(i)),ny=Math.abs(n.getY(i));uv.setXY(i,(nx>.5?p.getZ(i):p.getX(i))*.23,(ny>.5?p.getZ(i):p.getY(i))*.23);}}if(!this.batch.has(key))this.batch.set(key,[]);this.batch.get(key).push(b);g.dispose();}
 box(key,x,y,z,w,h,d,rx=0,ry=0,rz=0){this.add(new T.BoxGeometry(1,1,1),key,x,y,z,w,h,d,rx,ry,rz);}
 cyl(key,x,y,z,r,h,n=12){this.add(new T.CylinderGeometry(r,r,h,n),key,x,y,z);}
 rock(key,x,y,z,w,h,d,n=0){const geometry=new T.IcosahedronGeometry(1,n),background=d>=30&&Math.abs(x-this.game.level.centerAt(z))>30;let yaw=background?(rand(x+z)-.5)*.12:rand(x+z)*6;
  if(background){
   // Reserve the whole bent road and shrine court, using the transformed geometry rather than its nominal width.
   geometry.computeBoundingBox();const transform=new T.Object3D();transform.position.set(x,y,z);transform.scale.set(w,h,d);transform.rotation.set(.15,yaw,.1);transform.updateMatrix();const bounds=geometry.boundingBox.clone().applyMatrix4(transform.matrix),level=this.game.level;
   const centers=[level.centerAt(bounds.min.z),level.centerAt(bounds.max.z),...level.routes.filter(p=>p.z>=bounds.min.z&&p.z<=bounds.max.z).map(p=>p.x)];
   const left=Math.min(...centers)-25;let right=Math.max(...centers)+25;
   if(bounds.max.z>=level.shrine.z-24&&bounds.min.z<=level.shrine.z+24)right=Math.max(right,level.shrine.x+16);
   if(x<level.centerAt(z))x-=Math.max(0,bounds.max.x-left);else x+=Math.max(0,right-bounds.min.x);
  }
  this.add(geometry,key,x,y,z,w,h,d,.15,yaw,.1);
 }
 end(){for(const [key,gs]of this.batch){const geometry=new T.BufferGeometry();for(const name of ['position','normal','uv']){let n=0;for(const g of gs)n+=g.attributes[name]?.array.length||0;if(!n)continue;const array=new Float32Array(n);let o=0;for(const g of gs){if(g.attributes[name]){array.set(g.attributes[name].array,o);o+=g.attributes[name].array.length;}}geometry.setAttribute(name,new T.BufferAttribute(array,name==='uv'?2:3));}geometry.computeBoundingSphere();this.mesh(geometry,key,this.chunk);gs.forEach(g=>g.dispose());}this.batch.clear();}
 roof(x,y,z,w,d,levels=1){for(let k=0;k<levels;k++){const scale=1-k*.22,yy=y+k*3;this.box('wood',x,yy-1,z,w*scale*.86,2,d*scale*.8);for(let side of [-1,1]){this.box('metal',x+side*w*scale*.24,yy+.35,z,w*scale*.56,.22,d*scale+1,0,0,side*-.28);this.box('metal',x+side*w*scale*.5,yy-.1,z,.7,.18,d*scale+1.4,0,0,side*.22);for(let j=-3;j<=3;j++)this.box('stone',x+side*w*scale*.24,yy+.5,z+j*d*scale/7,w*scale*.55,.065,.08,0,0,side*-.28);}this.box('metal',x,yy+1,z,.35,.25,d*scale+1.8);}}
 arch(x,z,w,h,gothic=false){for(let side of [-1,1]){this.box('stone',x+side*w/2,h/2,z,1.4,h,1.8);this.box('accent',x+side*w/2,1,z,2,2,2.4);}if(gothic){for(let side of [-1,1])this.box('stone',x+side*w/4,h+1,z,w*.62,1,1.8,0,0,-side*.7);}else this.box('stone',x,h,z,w+3,1.5,2);}
 building(x,z,i){const side=Math.sign(x),y=rand(i+91)*4+6,w=10+rand(i)*5,d=10+rand(i+17)*5,theme=this.themeName;
  this.colliders.push(new T.Box3(new T.Vector3(x-w/2,0,z-d/2),new T.Vector3(x+w/2,theme==='celestial'?40+(i%5)*7:y+6,z+d/2)));
  if(theme==='japan'){this.box('stone',x,.6,z,w+1,1.2,d+1);this.box('wood',x,y*.5,z,w,y,d);this.roof(x,y,z,w+2,d+1,i%5===0?2:1);for(let j=-3;j<=3;j++){this.box('stone',x-side*(w/2+.02),y*.45,z+j*d/8,.12,y*.65,.75);this.box('wood',x-side*(w/2+.1),y*.45,z+j*d/8,.15,y*.68,.06);}for(let k=1;k<4;k++)this.box('wood',x-side*w/2,y*k/4,z,.25,.18,d+.5);this.box('accent',x-side*(w/2+1),3.8,z,2,.2,d+1,0,0,side*.1);for(let j=-1;j<=1;j++){this.cyl('wood',x-side*(w/2+1.3),1.8,z+j*d/2,.09,3.6);this.cyl('glow',x-side*(w/2+1.5),3,z+j*d/3,.28,.65);}}
  if(theme==='west'){this.box('wood',x,y/2,z,w,y,d);for(let k=0;k<12;k++)this.box(i%2?'stone':'wood',x-side*w/2,k*y/12,z,.12,.055,d);this.box('accent',x-side*w/2,y+1,z,.4,2.5,d);this.box('metal',x-side*(w/2+1),3,z,3,.15,d+2);for(let j=-2;j<=2;j++){this.cyl('wood',x-side*(w/2+2),1.5,z+j*d/4,.07,3);this.box('metal',x-side*(w/2+.06),2,z+j*d/4,.08,1.5,1);this.box('glow',x-side*(w/2+.1),2,z+j*d/4,.08,.65,.4);}this.box('wood',x-side*(w/2+1),.2,z,3,.4,d+2);this.box('stone',x,y+.15,z,w,.3,d);}
  if(theme==='cyber'){const h=y*3+rand(i+9)*25;this.box('stone',x,h/2,z,w,h,d);this.box('metal',x-side*(w/2+.2),h*.6,z,1.5,h*.8,1);for(let row=0;row<8;row++)for(let j=-2;j<=2;j++)this.box((row+j+i)%4?'metal':'glow',x-side*(w/2+.06),3+row*3,z+j*d/5,.12,1.4,1);this.box('accent',x-side*(w/2+.7),8,z,1,6,1.6);this.box('glow',x-side*(w/2+.9),8,z,.15,5.5,.2);this.cyl('metal',x,y*3,z,.1,12);this.box('metal',x-side*2,3,z,2,1.5,2);if(i%4===0){this.box('metal',0,15,z,50,1,3);for(let j=-12;j<=12;j+=3)this.box('glow',j,14.4,z,.5,.1,2);}}
  if(theme==='egypt'){this.box('stone',x,2,z,w,4,d);for(let k=0;k<5;k++)this.box('stone',x,4+k*1.3,z,w-k*1.6,1.3,d-k*1.3);for(let j=-1;j<=1;j++){this.cyl('stone',x-side*(w/2+1),4,z+j*d*.38,.75,8);this.cyl('accent',x-side*(w/2+1),6.5,z+j*d*.38,.82,.3);}this.box('accent',x-side*(w/2+.1),2.2,z,.12,1.2,d*.8);}
  if(theme==='ice'){this.box('stone',x,y/2,z,w,y,d);this.roof(x,y,z,w+2,d);this.box('ground',x,y+1,z,w+1,.35,d+1);for(let j=-3;j<=3;j++){this.add(new T.ConeGeometry(.18,2+rand(j+i)*2,5),'ground',x-side*(w/2+.5),y-1,z+j*d/7,1,1,1,Math.PI);this.box('wood',x-side*(w/2+.1),y*.5,z+j*d/7,.22,y,.2);}this.rock('accent',x+side*7,8,z,4,12,6,1);}
  if(theme==='gothic'){this.box('stone',x,y,z,w,y*2,d);for(let j=-2;j<=2;j++){this.box('metal',x-side*(w/2+.05),y,z+j*d/5,.12,y*1.25,1.5);this.box('glow',x-side*(w/2+.08),y,z+j*d/5,.14,y, .24);this.box('stone',x-side*(w/2+.7),y/2,z+j*d/5,1.2,y,1);this.add(new T.ConeGeometry(.8,3,4),'metal',x-side*(w/2+.7),y+1.5,z+j*d/5);}this.cyl('metal',x,y+4,z,1.3,14);for(let k=0;k<4;k++)this.cyl('accent',x,y+k*3,z,1.4,.2);}
  if(theme==='celestial')window.buildDecoTower(this,x,z,i);
 }
 build(){const g=this.game,th=this.themeName;this.scene.background=new T.Color(this.theme.sky);this.scene.fog=new T.FogExp2(this.theme.fog,th==='cyber'?.008:.0055);
  if(th==='ice'||th==='celestial'){const mat=new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{time:{value:0},ice:{value:th==='ice'?1:0}},vertexShader:'varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 p;uniform float time,ice;float hash(vec2 p){return fract(sin(dot(p,vec2(12.9898,78.233)))*43758.5453);}void main(){vec3 n=normalize(p);vec3 c=mix(vec3(.055,.075,.12),vec3(.012,.019,.04),max(0.,n.y));float star=step(.998,hash(floor(n.xz*420.)))*smoothstep(0.,.2,n.y);float curtain=pow(abs(sin(n.x*7.+sin(n.z*9.)+time*.1)),12.)*exp(-pow((n.y-.35)*5.,2.));float crack=1.-smoothstep(.005,.018,abs(fract(n.x*8.+n.y*3.+sin(n.y*27.)*.055)-.5));c+=star*.6+mix(vec3(.32,.15,.5)*crack*smoothstep(0.,.3,n.y),vec3(.08,.36,.27)*curtain,ice);gl_FragColor=vec4(c,1.);}'});this.materials.set('sky',mat);this.sky=this.mesh(new T.SphereGeometry(210,32,18),mat);this.sky.castShadow=this.sky.receiveShadow=false;}
  for(let k=0;k<Math.ceil(g.level.length/120);k++){this.begin(k*120+60);const z=k*120;this.box('ground',g.level.centerAt(z+60),-1.25,z+60,180,1,121);for(let seg=0;seg<12;seg++){const zz=z+seg*10+5,cx=g.level.centerAt(zz);this.box('ground',cx,-.3,zz,44,.6,10.2);for(let side of [-1,1])this.box('stone',cx+side*21,-1,zz,2,2,10.2);}
   for(let j=0;j<5;j++)for(let side of [-1,1])this.building(g.level.centerAt(z+12+j*24)+side*(29+rand(j+k*19)*3),z+12+j*24,k*11+j+(side+1)*40);
   if(['japan','gothic'].includes(th)){for(let side of [-1,1]){for(let seg=0;seg<12;seg++)this.box('metal',g.level.centerAt(z+seg*10+5)+side*18,.025,z+seg*10+5,3,.05,10.2);for(let j=0;j<12;j++)this.box('stone',g.level.centerAt(z+j*10)+side*20,1.2,z+j*10, .4,2.4,.4);for(let seg=0;seg<12;seg++)this.box('wood',g.level.centerAt(z+seg*10+5)+side*20,2.2,z+seg*10+5,.25,.25,10.2);}}
   if(th==='west'){for(let side of [-1,1])for(let seg=0;seg<12;seg++)this.box('metal',g.level.centerAt(z+seg*10+5)+side*1.7,.035,z+seg*10+5,.15,.1,10.2);for(let j=0;j<40;j++)this.box('wood',g.level.centerAt(z+j*3),.01,z+j*3,5,.12,.35);for(let side of [-1,1]){this.rock('stone',side*55,12,z+60,20,24,60,1);this.cyl('wood',side*17,6,z+25,.12,12);this.box('wood',side*17,10,z+25,4,.16,.2);}}
   if(th==='egypt')for(let side of [-1,1])this.rock('ground',side*58,7,z+60,25,14,65,2);
   if(th==='ice')for(let side of [-1,1])this.rock('accent',side*55,16,z+60,18,32,60,1);
   if(th==='celestial'&&k%2===1)window.buildDecoRail(this,g,z+60);
   if(k%2===1){if(th==='japan'){this.box('wood',0,7,z+60,42,.55,1.4);for(let side of [-1,1])this.cyl('accent',side*17,3.5,z+60,.45,7);this.roof(0,8,z+60,40,3);}else if(th==='gothic'||th==='egypt'||th==='celestial')this.arch(0,z+60,37,15,th==='gothic');}
   for(const o of g.obstacles)if(o.z>=z&&o.z<z+120){this.box(th==='west'?'wood':'stone',o.x,o.h/2,o.z,o.w*2,o.h,o.d*2);this.colliders.push(new T.Box3(new T.Vector3(o.x-o.w,0,o.z-o.d),new T.Vector3(o.x+o.w,o.h,o.z+o.d)));}
   this.end();
  }
  this.begin(g.level.shrine.z);this.box('stone',g.level.centerAt(g.level.shrine.z)+30,-.2,g.level.shrine.z,24,.4,36);for(let side of [-1,1])this.cyl('accent',g.level.shrine.x+side*5,3,g.level.shrine.z,.5,6);this.end();
  for(const ramp of g.level.ramps){const {start,length,height}=ramp;this.begin(start+length/2);for(let j=0;j<length;j++){const zz=start+j+.5,h=g.walkHeight(g.level.centerAt(zz),zz);this.box('stone',g.level.centerAt(zz),h-.25,zz,34,.5,1.01);if(j%3===0)for(let side of [-1,1])this.box('wood',g.level.centerAt(zz)+side*16,h+1.1,zz,.18,2.2,.18);}for(let side of [-1,1])this.box('metal',g.level.centerAt(start+length/2)+side*16,height+1.1,start+length/2,.2,.2,length-ramp.rise*2);this.end();}
  this.begin((g.level.bossZ+0));if(th==='japan'){this.roof(0,19,(g.level.bossZ+42),30,18,3);this.arch(0,(g.level.bossZ+28),17,10);this.cyl('metal',0,10,(g.level.bossZ+40),3,5);}if(th==='west'){this.box('wood',0,6,(g.level.bossZ+40),32,12,14);for(let x=-12;x<=12;x+=6)this.box('metal',x,7,(g.level.bossZ+32.8),3,5,.2);this.box('accent',0,15,(g.level.bossZ+40),35,5,1);this.cyl('metal',-13,4,(g.level.bossZ+0),1,8);}if(th==='cyber'){this.cyl('metal',0,25,(g.level.bossZ+35),12,50,8);for(let y=3;y<50;y+=4)this.cyl('glow',0,y,(g.level.bossZ+35),12.1,.18,8);}if(th==='egypt'){for(let x of [-13,13]){this.box('stone',x,6,(g.level.bossZ+30),7,12,7);this.rock('stone',x,16,(g.level.bossZ+30),4,6,4,2);this.box('accent',x,21,(g.level.bossZ+30),8,2,4);}this.arch(0,(g.level.bossZ+40),20,22);}if(th==='ice'){this.arch(0,(g.level.bossZ+35),26,20);for(let x of [-17,17]){this.cyl('stone',x,12,(g.level.bossZ+30),5,24,8);this.add(new T.ConeGeometry(7,10,8),'ground',x,29,(g.level.bossZ+30));}}if(th==='gothic'){this.box('stone',0,16,(g.level.bossZ+45),30,32,12);for(let x of [-14,14]){this.box('stone',x,23,(g.level.bossZ+40),7,46,10);this.add(new T.ConeGeometry(6,18,8),'metal',x,55,(g.level.bossZ+40));}this.arch(0,(g.level.bossZ+37),12,17,true);this.add(new T.TorusGeometry(6,.35,8,40),'accent',0,26,(g.level.bossZ+38));this.cyl('metal',0,8,(g.level.bossZ+25),4,8);}if(th==='celestial')window.buildDecoTower(this,this.game.level.centerAt(g.level.bossZ),g.level.bossZ+40,0,true);this.end();
  for(const gate of g.gates){const root=new T.Group();root.position.set(gate.x,0,gate.z);this.root.add(root);const m=this.mesh(new T.BoxGeometry(39,3.8,.55),new T.MeshStandardMaterial({color:SevenWorlds.elements[gate.type].color,transparent:true,opacity:.32,emissive:SevenWorlds.elements[gate.type].color,emissiveIntensity:.25}),root);m.position.y=1.9;this.materials.set('gate'+gate.id,m.material);for(let i=-6;i<=6;i++){const x=i*3;
   if(gate.type===1){for(let j=0;j<2;j++){const plank=this.mesh(new T.BoxGeometry(.25,4.3,.35),'wood',root);plank.position.set(x,.9+j*.6,0);plank.rotation.z=(j?1:-1)*.7;}const band=this.mesh(new T.BoxGeometry(3.1,.13,.4),'metal',root);band.position.set(x,1.8,.1);}
   if(gate.type===0){const swirl=this.mesh(new T.TorusGeometry(1.5,.04,5,40,5.2),m.material,root);swirl.position.set(x,1.5,0);swirl.rotation.set(i*.25,.3,i*.9);swirl.userData.swirl=true;}
   if(gate.type===2){const post=this.mesh(new T.CylinderGeometry(.35,.6,3.4,6),'metal',root);post.position.set(x,1.7,0);const strip=this.mesh(new T.BoxGeometry(.08,2.4,.5),m.material,root);strip.position.set(x,1.9,-.1);}
   if(gate.type===3){const flame=this.mesh(new T.ConeGeometry(.7,4.2,5),'glow',root);flame.position.set(x,1.9,0);flame.userData.flame=i;const coal=this.mesh(new T.DodecahedronGeometry(.75),'wood',root);coal.position.set(x,.3,0);}
   if(gate.type===4){const rock=this.mesh(new T.DodecahedronGeometry(1),'stone',root);rock.position.set(x,-.4,0);rock.scale.set(1.8,.6,2.5);const rune=this.mesh(new T.OctahedronGeometry(.24),m.material,root);rune.position.set(x,.7,0);}
  }this.gates.push({root,gate});}
  for(const orb of g.orbs){const root=new T.Group();root.position.set(orb.x,2,orb.z);this.root.add(root);const mat=new T.MeshPhysicalMaterial({color:SevenWorlds.elements[orb.type].color,metalness:.35,roughness:.1,transparent:true,opacity:.55,side:T.DoubleSide});this.materials.set('orb'+orb.type,mat);this.mesh(new T.IcosahedronGeometry(.8,1),mat,root);const core=this.mesh(new T.IcosahedronGeometry(.32,2),new T.MeshBasicMaterial({color:SevenWorlds.elements[orb.type].color}),root);this.materials.set('core'+orb.type,core.material);for(let i=0;i<3;i++){const ring=this.mesh(new T.TorusGeometry(.55,.035,5,32),core.material,root);ring.rotation.set(i*.8,i*1.2,i*.4);}this.orbs.push({root,orb});}
  for(const cp of g.level.checkpoints){const m=this.mesh(new T.TorusGeometry(2,.045,5,48),'glow');m.rotation.x=Math.PI/2;m.position.set(g.level.centerAt(cp),.07,cp);}
  this.shrine=this.mesh(new T.OctahedronGeometry(1.3),'glow');this.shrine.position.set(g.level.shrine.x,2,g.level.shrine.z);
  for(const relay of g.relays){const root=new T.Group();this.root.add(root);root.position.set(relay.x,g.walkHeight(relay.x,relay.z),relay.z);const c=this.mesh(new T.CylinderGeometry(.6,1,5,6),'metal',root);c.position.y=2.5;const light=this.mesh(new T.CylinderGeometry(.2,.2,4,6),'glow',root);light.position.y=3;this.relays.push({root,relay});}
  for(const barrel of g.barrels){const m=this.mesh(new T.CylinderGeometry(.65,.65,1.8,12),'accent');m.position.set(barrel.x,.9,barrel.z);this.barrels.push({root:m,barrel});}
  const count=500,positions=new Float32Array(count*6);this.weatherPositions=positions;this.weather=this.mesh(new T.BufferGeometry(),'ground');this.root.remove(this.weather);this.weather.geometry.dispose();this.geo.delete(this.weather.geometry);const geo=this.geometry(new T.BufferGeometry());geo.setAttribute('position',new T.BufferAttribute(positions,3));const mat=new T.LineBasicMaterial({color:this.theme.light,transparent:true,opacity:th==='ice'?.55:.19});this.materials.set('weather',mat);this.weather=new T.LineSegments(geo,mat);this.weather.frustumCulled=false;this.root.add(this.weather);
 }
 update(time,quality){this.detail?.update(time,quality);const g=this.game,p=g.player;if(this.sky){this.sky.position.set(p.x,0,p.z);this.sky.material.uniforms.time.value=time;}for(const chunk of this.chunks)chunk.visible=Math.abs(chunk.userData.z-p.z)<190;for(const {root,orb}of this.orbs){root.visible=!orb.collected;root.rotation.set(time*.3,time*.8,time*.17);root.position.y=2+Math.sin(time*2+orb.type)*.2;}for(const {root,gate}of this.gates){root.visible=!gate.open;root.children[0].material.opacity=.07+.03*Math.sin(time*1.5);for(const child of root.children){if(child.userData.swirl)child.rotation.z+=.012;if(child.userData.flame!==undefined){child.scale.y=.8+Math.sin(time*9+child.userData.flame)*.2;child.rotation.z=Math.sin(time*6+child.userData.flame)*.08;}}}for(const {root,relay}of this.relays)root.visible=relay.hp>0;for(const {root,barrel}of this.barrels)root.visible=barrel.hp>0;this.shrine.visible=!g.shrine.done;this.shrine.rotation.y=time*.4;
  this.weather.visible=['japan','cyber','ice','gothic'].includes(this.themeName);if(this.weather.visible){const n=quality==='low'?160:500,v=this.weatherPositions,snow=this.themeName==='ice';for(let i=0;i<n;i++){const x=p.x+(rand(i*7)-.5)*70,y=(rand(i*3+1)*35-time*(snow?2:17))%35,z=p.z+(rand(i*5+3)-.5)*110;v.set([x,y<0?y+35:y,z,x+.13,(y<0?y+35:y)+(snow?.13:1.2),z+.13],i*6);}this.weather.geometry.setDrawRange(0,n*2);this.weather.geometry.attributes.position.needsUpdate=true;}
 }
 cameraPosition(target,desired){const dir=desired.clone().sub(target),len=dir.length();dir.normalize();const ray=new T.Ray(target,dir),hit=new T.Vector3();let d=len;for(const box of this.colliders)if(ray.intersectBox(box,hit)){const n=target.distanceTo(hit);if(n<d)d=Math.max(2,n-.7);}return target.clone().addScaledVector(dir,d);}
 dispose(){this.detail?.dispose();this.scene.remove(this.root);for(const g of this.geo)g.dispose();for(const m of this.materials.values())m.dispose();for(const t of this.textures)t.dispose();this.root.clear();this.chunks=[];this.colliders=[];}
}
window.WorldView=WorldView;window.WorldThemes=themes;
})();
