const {test}=require('node:test'),assert=require('node:assert/strict');
const {CampaignGame,CampaignState}=require('../campaign.js');global.THREE=require('../three.min.js');global.window={};require('../impact-fx.js');require('../audio.js');
function arena(tier=1){const g=new CampaignGame(new CampaignState(),{demo:true,tier});g.gates=[];g.orbs=[];g.encounters=[];g.obstacles=[];g.shrine.done=true;g.enemyStep=()=>{};g.element=0;return g;}
test('Air critical chance progresses from 25 to 40 percent and matches a deterministic large sample',()=>{for(let tier=1;tier<=7;tier++){const g=arena(tier);assert.equal(g.airCritChance,.25+(tier-1)*.025);let crits=0;for(let i=0;i<10000;i++)crits+=g.rollCritical()?1:0;assert.ok(Math.abs(crits/10000-g.airCritChance)<.02);}const g=arena();for(let el=1;el<5;el++){g.element=el;g.random=()=>0;assert.equal(g.rollCritical(),false);}});
test('Air critical hits double actual damage, stack with weakness, and mark damage events',()=>{const g=arena();g.random=()=>0;const e=g.makeEnemy(0,20);e.weakness=0;g.cast(e);assert.equal(e.max-e.hp,24);assert.equal(g.events.find(e=>e.type==='damage').critical,true);assert.equal(g.events.find(e=>e.type==='cast').critical,true);g.events=[];g.random=()=>1;const before=e.hp;g.cast(e);assert.equal(before-e.hp,12);assert.equal(g.events.find(e=>e.type==='damage').critical,false);});
test('Air critical results are identical across 30, 60 and 120 FPS',()=>{const results=[30,60,120].map(fps=>{const g=arena(7);const e=g.makeEnemy(0,20);e.hp=e.max=1e6;e.weakness=-1;let crits=0;for(let i=0;i<fps*10;i++){g.advance(1/fps,{cast:true});crits+=g.events.filter(e=>e.type==='cast'&&e.critical).length;g.events=[];}return{damage:e.max-e.hp,crits};});assert.deepEqual(results[0],results[1]);assert.deepEqual(results[1],results[2]);assert.ok(results[0].crits>0);});
test('Each elemental impact activates its own geometry and all effect pools remain bounded',()=>{const fx=new window.ImpactFX(new THREE.Scene()),game={walkHeight:()=>0};const kinds={0:'air',1:'fire',3:'foam',4:'stone'};for(const [el,kind] of Object.entries(kinds)){fx.reset();fx.event({type:'cast',element:+el,tier:7,x:0,y:0,z:0,dx:0,dz:1,range:20,impactX:0,impactZ:20,critical:true},0);fx.update(.2,game);assert.ok(fx.meshes[kind].count>0);for(const other of ['air','fire','foam','stone'])if(other!==kind)assert.equal(fx.meshes[other].count,0);}
 const counts=Object.values(fx.meshes).map(m=>m.geometry.attributes.position.count);for(let i=0;i<3000;i++){const t=i/60;fx.event({type:'cast',element:i%5,tier:7,x:1,y:0,z:3,dx:.6,dz:.8,range:30,critical:true},t);fx.update(t+.1,game,i%2===0);assert.ok(fx.jobs.length<=24);for(const m of Object.values(fx.meshes))assert.ok(m.count<=m.instanceMatrix.count);}
 for(const m of Object.values(fx.meshes))for(const n of m.instanceMatrix.array)assert.ok(Number.isFinite(n));assert.deepEqual(Object.values(fx.meshes).map(m=>m.geometry.attributes.position.count),counts);fx.reset();assert.equal(fx.jobs.length,0);assert.ok(Object.values(fx.meshes).every(m=>m.count===0));});
test('Lightning loading fallback is a single noise-based thunder recipe, with no added electrical impact chatter',()=>{const audio=new window.ElementAudio(),layers=[];audio.context={currentTime:0};audio.layer=o=>layers.push(o);audio.cast(2);assert.equal(layers.length,4);assert.ok(layers.every(l=>l.noise));assert.ok(layers.some(l=>l.attack<=.003));assert.ok(layers.some(l=>l.duration>=2));audio.impact(2);assert.equal(layers.length,4);for(let i=1;i<7;i++){audio.context.currentTime=i*.1;audio.cast(2);}assert.equal(layers.length,4);audio.context.currentTime=.71;audio.cast(2);assert.equal(layers.length,8);});
test('Air audio has a short rising whoosh and a noise tail; muting prevents new voices',()=>{const audio=new window.ElementAudio(),layers=[];audio.context={currentTime:0};audio.layer=o=>layers.push(o);audio.cast(0);assert.ok(layers.every(l=>l.noise&&l.duration<=.7));assert.ok(layers.some(l=>l.endCutoff>l.cutoff&&l.attack<.1));assert.ok(layers.some(l=>l.delay>0));const count=layers.length;audio.enabled=false;audio.context.currentTime=5;audio.cast(0);assert.equal(layers.length,count);});
