const {test}=require('node:test'),assert=require('node:assert/strict');const {CampaignGame,CampaignState,dist}=require('../campaign.js');
test('Full campaign completes with normal health and automatic targeting',()=>{let c=new CampaignState();const log=[];for(let id=0;id<7;id++){const g=new CampaignGame(c,{level:id});let steps=0,phase2=false;while(!g.finished&&steps++<60*1800){const p=g.player;let dest={x:g.level.centerAt(g.level.bossZ),z:g.level.bossZ+10},cast=false;const nearby=g.enemies.filter(e=>e.hp>0&&e.active&&dist(e,p)<45);if(g.relays.some(r=>r.hp>0)&&g.boss.active){dest=g.relays.find(r=>r.hp>0);g.element=2;cast=true;}else if(nearby.length){dest=nearby.sort((a,b)=>dist(a,p)-dist(b,p))[0];g.element=dest.role==='shield'&&g.canUse(4)?4:g.canUse(2)?2:g.canUse(1)?1:g.element;cast=true;}else{const orb=g.currentOrb,gate=g.currentGate,enc=g.encounters.find(e=>!e.done);if(orb&&orb.z<Math.min(gate?.z||9999,enc?.z||9999))dest=orb;else if(gate&&gate.z< (enc?.z||9999)){dest=gate;g.element=gate.type;cast=dist(p,gate)<31;}else if(enc)dest={x:g.level.centerAt(enc.z),z:enc.z};}
const d=dist(p,dest);let mx=dest.x-p.x,mz=dest.z-p.z;if(cast&&d<22&&g.visibleTarget(dest)){mx=mz=0;}else{const len=Math.hypot(mx,mz)||1;mx/=len;mz/=len;}for(const o of g.obstacles)if(Math.abs(p.z-o.z)<7&&Math.abs(p.x-o.x)<o.w+1.2){mx=p.x<o.x?-1:1;mz=.15;}if(g.telegraphs.some(t=>t.life<.6&&Math.hypot(t.x-p.x,t.z-p.z)<t.r+2)){mx=p.x<g.level.centerAt(p.z)?1:-1;mz=0;}g.advance(1/60,{mx,mz,cast});if(g.boss.phase===2)phase2=true;g.events=[];}
assert.ok(g.finished,`World ${id+1} blocked at ${g.player.x},${g.player.z}, gate ${g.currentGate?.z}, enemy ${g.enemies.filter(e=>e.hp>0&&e.active).map(e=>e.role+':'+e.z)}`);assert.ok(phase2);assert.equal(g.encounters.filter(e=>e.done).length,3);assert.ok(g.gates.every(g=>g.open));if(id===0)assert.equal(g.unlocks.size,5);assert.ok(c.completed.includes(id));c.upgradeAll();log.push({world:id+1,simulatedSeconds:Math.round(steps/60)});c=CampaignState.parse(c.serialize());}
assert.equal(c.completed.length,7);assert.equal(c.earned,30);assert.ok(log.reduce((sum,x)=>sum+x.simulatedSeconds,0)<=840,'Main route must leave room for menus within the 15-minute target');assert.ok(log.every(x=>x.simulatedSeconds<=180),'Each world remains a short mission');console.log('Automated normal-health campaign traversal:',JSON.stringify(log));});


test('Showcase completes through both transformations and player-triggered ending',()=>{let c=new CampaignState();const before=c.serialize();const log=[];for(let id=0;id<1;id++){const g=new CampaignGame(c,{mode:'showcase'});let steps=0,phase2=false;while(!g.finished&&steps++<60*1800){const p=g.player;let dest={x:g.level.centerAt(g.level.bossZ),z:g.level.bossZ+10},cast=false;const nearby=g.enemies.filter(e=>e.hp>0&&e.active&&dist(e,p)<45);if(g.relays.some(r=>r.hp>0)&&g.boss.active){dest=g.relays.find(r=>r.hp>0);g.element=2;cast=true;}else if(nearby.length){dest=nearby.sort((a,b)=>dist(a,p)-dist(b,p))[0];g.element=dest.role==='shield'&&g.canUse(4)?4:g.canUse(2)?2:g.canUse(1)?1:g.element;cast=true;}else{const orb=g.currentOrb,gate=g.currentGate,enc=g.encounters.find(e=>!e.done);if(orb&&orb.z<Math.min(gate?.z||9999,enc?.z||9999))dest=orb;else if(gate&&gate.z< (enc?.z||9999)){dest=gate;g.element=gate.type;cast=dist(p,gate)<31;}else if(enc)dest={x:g.level.centerAt(enc.z),z:enc.z};}
const d=dist(p,dest);let mx=dest.x-p.x,mz=dest.z-p.z;if(cast&&d<22&&g.visibleTarget(dest)){mx=mz=0;}else{const len=Math.hypot(mx,mz)||1;mx/=len;mz/=len;}for(const o of g.obstacles)if(Math.abs(p.z-o.z)<7&&Math.abs(p.x-o.x)<o.w+1.2){mx=p.x<o.x?-1:1;mz=.15;}if(g.telegraphs.some(t=>t.life<.6&&Math.hypot(t.x-p.x,t.z-p.z)<t.r+2)){mx=p.x<g.level.centerAt(p.z)?1:-1;mz=0;}if(g.finishReady){cast=!g.lastInput.cast;mx=mz=0;}g.advance(1/60,{mx,mz,cast});if(g.boss.phase===2)phase2=true;g.events=[];}
assert.ok(g.finished,`World ${id+1} blocked at ${g.player.x},${g.player.z}, gate ${g.currentGate?.z}, enemy ${g.enemies.filter(e=>e.hp>0&&e.active).map(e=>e.role+':'+e.z)}`);assert.ok(phase2);assert.equal(g.encounters.filter(e=>e.done).length,3);assert.ok(g.gates.every(g=>g.open));if(id===0)assert.equal(g.unlocks.size,5);assert.equal(c.serialize(),before);assert.equal(g.tier,7);log.push({world:id+1,simulatedSeconds:Math.round(steps/60)});c=CampaignState.parse(c.serialize());}
assert.equal(c.completed.length,0);assert.equal(c.earned,0);assert.ok(log.reduce((sum,x)=>sum+x.simulatedSeconds,0)<=840,'Main route must leave room for menus within the 15-minute target');assert.ok(log.every(x=>x.simulatedSeconds<=180),'Each world remains a short mission');console.log('Automated showcase traversal:',JSON.stringify(log));});

