const {test}=require('node:test'),assert=require('node:assert/strict');
const {CampaignState,CampaignGame,levels,damageScale,dist}=require('../campaign.js');
function sandbox(tier=1){const g=new CampaignGame(new CampaignState(),{demo:true,tier});g.gates=[];g.orbs=[];g.encounters=[];g.obstacles=[];g.boss.active=false;g.shrine.done=true;return g;}
test('new campaign starts with no elements and discovery saves the crystal',()=>{const c=new CampaignState(),g=new CampaignGame(c);assert.equal(g.unlocks.size,0);g.player.x=g.orbs[0].x;g.player.z=g.orbs[0].z;g.advance(1/30,{});assert.deepEqual([...g.unlocks],[1]);assert.deepEqual(c.unlocked,[1]);assert.ok(g.events.some(e=>e.type==='unlocked'));const loaded=new CampaignGame(CampaignState.parse(c.serialize()));assert.equal(loaded.canUse(1),true);assert.equal(loaded.player.z,8);});
test('30, 60 and 120 FPS produce the same sustained damage, sword combo and movement',()=>{const samples=[30,60,120].map(fps=>{const g=sandbox();const e=g.makeEnemy(0,25);e.hp=e.max=100000;e.cooldown=1e6;g.enemyStep=()=>{};for(let i=0;i<fps*12;i++){g.advance(1/fps,{cast:true});g.events=[];}const damage=100000-e.hp;const h=sandbox();for(let i=0;i<fps*8;i++)h.advance(1/fps,{mx:.5,mz:.5,sword:true});return{damage,x:h.player.x,z:h.player.z,combo:h.combo};});assert.deepEqual(samples[0],samples[1]);assert.deepEqual(samples[1],samples[2]);});
test('all seven damage tiers grow exactly by the selected multipliers',()=>{const losses=[];for(let tier=1;tier<=7;tier++){const g=sandbox(tier),e=g.makeEnemy(0,20);e.weakness=-1;g.cast(e);losses.push(e.max-e.hp);}losses.forEach((x,i)=>assert.ok(Math.abs(x-8*damageScale[i])<1e-8));});
test('campaign tiers follow mission entry and demo cannot award progress',()=>{const c=new CampaignState();const before=c.serialize();const g=new CampaignGame(c,{demo:true,level:6,tier:7});g.complete();g.respawn();assert.equal(c.serialize(),before);for(let i=0;i<7;i++){const c=new CampaignState();c.highest=i;const g=new CampaignGame(c,{level:i});assert.equal(g.tier,i+1);if(i)assert.equal(g.unlocks.size,5);}});
test('specialization ranks and refunds conserve all thirty earned points',()=>{const c=new CampaignState();c.completed=[0,1,2,3,4,5];c.highest=6;for(let i=0;i<3;i++)assert.equal(c.upgrade(1,'impact'),true);assert.equal(c.upgrade(1,'impact'),false);for(let i=0;i<3;i++)c.upgrade(3,'control');assert.equal(c.points,24);assert.equal(c.upgradeAll(),24);assert.equal(c.points,0);assert.equal(c.upgrade(2,'impact'),false);c.refund();assert.equal(c.points,30);assert.equal(c.spent,0);assert.equal(CampaignState.parse(c.serialize()).points,30);});
test('invalid imports are rejected',()=>{for(const mutate of [c=>c.version=999,c=>c.level=9,c=>c.unlocked=[9],c=>c.completed=[0,0],c=>c.specializations[0].impact=4,c=>c.specializations[0].control=1,c=>c.snapshot={level:0,checkpoint:20,gates:[],encounters:[]}]){const c=new CampaignState();mutate(c);assert.throws(()=>CampaignState.parse(JSON.stringify(c)));}assert.throws(()=>CampaignState.parse('{'));});
test('death restores the latest checkpoint while retaining earned elements',()=>{const c=new CampaignState(),g=new CampaignGame(c);g.unlocks.add(1);g.gates[0].open=true;g.checkpointIndex=1;g.checkpoint={x:g.level.centerAt(g.level.checkpoints[1]),z:g.level.checkpoints[1]};g.saveCheckpoint();g.player.z=170;g.unlocks.add(0);g.saveCheckpoint();g.player.hp=1;g.damage(10);assert.equal(g.player.z,g.level.checkpoints[1]);assert.equal(g.player.hp,100);assert.equal(g.canUse(0),true);assert.equal(g.gates[0].open,true);assert.equal(c.deaths,1);});
test('target selection respects gate and obstacle visibility',()=>{const g=sandbox(),e=g.makeEnemy(0,25);g.obstacles=[{x:0,z:15,w:3,d:3,h:3}];assert.equal(g.acquireTarget(),null);g.obstacles=[];assert.equal(g.acquireTarget().id,e.id);g.gates=[{x:0,z:18,open:false}];assert.equal(g.visibleTarget(e),false);});
test('water heals only on its own killing blow and earth reduces damage by 40 percent',()=>{const g=sandbox();g.player.hp=50;const e=g.makeEnemy(0,20);g.hit(e,1,3);assert.equal(g.player.hp,50);g.hit(e,1000,3);assert.equal(g.player.hp,60);const e2=g.makeEnemy(0,20);g.hit(e2,1000,1);assert.equal(g.player.hp,60);g.shield=1;g.damage(10);assert.equal(g.player.hp,54);g.player.invincible=0;g.shield=0;g.damage(10);assert.equal(g.player.hp,44);});
test('four reactions unlock at Tier 5, and bosses stagger instead of stun locking',()=>{for(const [first,next,name]of [[3,2,'Conduct'],[1,0,'Wildfire'],[3,1,'Steam'],[4,1,'Molten']]){const g=sandbox(5),e=g.makeEnemy(0,20);g.time=1;g.hit(e,1,first);g.hit(e,1,next);assert.ok(g.events.some(x=>x.type==='reaction'&&x.name===name));}const g=sandbox(4),e=g.makeEnemy(0,20);g.time=1;g.hit(e,1,3);g.hit(e,1,2);assert.ok(!g.events.some(x=>x.type==='reaction'));const h=sandbox(5);h.boss.active=true;h.time=1;h.hit(h.boss,1,3);h.hit(h.boss,1,2);assert.ok(!h.boss.status.stun);});
test('side shrine and walkable ramps are reachable without jumping',()=>{const g=sandbox();assert.equal(g.validPosition(g.level.shrine.x,g.level.shrine.z,g.level.shrine.z-1).x,g.level.shrine.x);assert.equal(g.walkHeight(g.level.centerAt(220),220),1);assert.equal(g.walkHeight(g.level.centerAt(230),230),2);assert.equal(g.walkHeight(g.level.centerAt(245),245),0);});
test('every guardian reaches phase two, and Grid Executor requires pylons',()=>{for(let id=0;id<7;id++){const g=new CampaignGame(new CampaignState(),{demo:true,level:id});g.player.z=g.level.bossZ-20;g.boss.active=true;if(id===2){const hp=g.boss.hp;g.hit(g.boss,100,1);assert.equal(g.boss.hp,hp);g.relays.forEach(r=>g.hit(r,999,2));}g.hit(g.boss,g.boss.max*.6,0);g.enemyStep(g.boss,1/60);assert.equal(g.boss.phase,2);g.hit(g.boss,99999,0);assert.equal(g.finished,true);}});
test('persistent damage and enemy warning queues remain bounded under sustained Tier 7 attacks',()=>{const g=sandbox(7),e=g.makeEnemy(0,20);e.hp=e.max=1e9;g.enemyStep=()=>{};let maxFields=0;for(let i=0;i<60*180;i++){g.element=Math.floor(i/120)%5;g.advance(1/60,{cast:true,tempest:true});maxFields=Math.max(maxFields,g.fields.length);g.events=[];}assert.ok(maxFields<=16);assert.ok(g.telegraphs.length<=30);});
test('all seven missions: discovery, traversal, encounters, checkpoints, phases and ending',()=>{let c=new CampaignState();const log=[];for(let id=0;id<7;id++){const g=new CampaignGame(c,{level:id});g.player.invincible=1e9;let steps=0,phase2=false;while(!g.finished&&steps++<60*1800){const p=g.player;let dest={x:g.level.centerAt(g.level.bossZ),z:g.level.bossZ+10},cast=false;const nearby=g.enemies.filter(e=>e.hp>0&&e.active&&dist(e,p)<45);if(g.relays.some(r=>r.hp>0)&&g.boss.active){dest=g.relays.find(r=>r.hp>0);g.element=2;cast=true;}else if(nearby.length){dest=nearby.sort((a,b)=>dist(a,p)-dist(b,p))[0];g.element=dest.role==='shield'&&g.canUse(4)?4:g.canUse(2)?2:g.canUse(1)?1:g.element;cast=true;}else{const orb=g.currentOrb,gate=g.currentGate,enc=g.encounters.find(e=>!e.done);if(orb&&orb.z<Math.min(gate?.z||9999,enc?.z||9999))dest=orb;else if(gate&&gate.z< (enc?.z||9999)){dest=gate;g.element=gate.type;cast=dist(p,gate)<31;}else if(enc)dest={x:g.level.centerAt(enc.z),z:enc.z};}
const d=dist(p,dest);let mx=dest.x-p.x,mz=dest.z-p.z;if(cast&&d<22&&g.visibleTarget(dest)){mx=mz=0;}else{const len=Math.hypot(mx,mz)||1;mx/=len;mz/=len;}for(const o of g.obstacles)if(Math.abs(p.z-o.z)<7&&Math.abs(p.x-o.x)<o.w+1.2){mx=p.x<o.x?-1:1;mz=.15;}g.advance(1/60,{mx,mz,cast,manualTarget:cast&&g.visibleTarget(dest)?dest:undefined});if(g.boss.phase===2)phase2=true;g.events=[];}
assert.ok(g.finished,`World ${id+1} blocked at ${g.player.x},${g.player.z}, gate ${g.currentGate?.z}, enemy ${g.enemies.filter(e=>e.hp>0&&e.active).map(e=>e.role+':'+e.z)}`);assert.ok(phase2);assert.equal(g.encounters.filter(e=>e.done).length,3);assert.ok(g.gates.every(g=>g.open));if(id===0)assert.equal(g.unlocks.size,5);assert.ok(c.completed.includes(id));c.upgradeAll();log.push({world:id+1,simulatedSeconds:Math.round(steps/60)});c=CampaignState.parse(c.serialize());}
assert.equal(c.completed.length,7);assert.equal(c.earned,30);assert.ok(log.reduce((sum,x)=>sum+x.simulatedSeconds,0)<=840,'Main route must leave room for menus within the 15-minute target');assert.ok(log.every(x=>x.simulatedSeconds<=180),'Each world remains a short mission');console.log('Automated campaign traversal (invulnerable test driver):',JSON.stringify(log));});

test('existing version-one checkpoint saves resume on the shortened routes without losing progression',()=>{
 for(let id=0;id<7;id++)for(let checkpoint=0;checkpoint<6;checkpoint++){
  const oldSave={version:1,level:id,highest:id,completed:Array.from({length:id},(_,i)=>i),unlocked:[1,0,2,3,4],specializations:Array.from({length:5},(_,i)=>({impact:i===1&&id>0?1:0,control:0})),mastery:[],time:4800,deaths:2,snapshot:{level:id,checkpoint,gates:[0],encounters:[0],shrine:true}};
  const c=CampaignState.parse(JSON.stringify(oldSave)),g=new CampaignGame(c);
  assert.equal(g.player.z,levels[id].checkpoints[checkpoint]);assert.equal(g.player.x,levels[id].centerAt(g.player.z));assert.equal(g.tier,id+1);
  assert.ok(g.gates[0].open);assert.ok(g.encounters[0].done);assert.ok(g.shrine.done);assert.equal(g.unlocks.size,5);assert.equal(c.time,4800);assert.equal(c.deaths,2);
  assert.equal(c.completed.length,id);assert.equal(c.specializations[1].impact,id>0?1:0);
 }
});
