const assert=require('node:assert/strict');
global.THREE=require('../three.min.js');global.window={};require('../effects.js');
const {ElementEffects}=window;let passed=0;
function test(name,fn){fn();console.log('PASS '+name);passed++;}
const fx=new ElementEffects(new THREE.Scene());
function cast(el,t,ultimate=false){fx.cast({x:1,z:2,dx:0,dz:1,element:el,ultimate},t,25);fx.update(t);}
test('Regular fire, air, and lightning activate their distinct continuous geometry',()=>{for(const [el,key] of [[1,'fire'],[0,'wind'],[2,'electric']]){fx.reset();cast(el,1);assert(fx[key].root.visible);for(const other of ['fire','wind','electric'])if(other!==key)assert(!fx[other].root.visible);}});
test('Continuous channels stop after casting ends',()=>{cast(1,2);fx.update(2.5);assert(!fx.fire.root.visible);cast(2,3);fx.update(3.5);assert(!fx.electric.root.visible);});
test('Wind and flame ribbons retain finite vertices throughout animation',()=>{for(const [el,key] of [[1,'fire'],[0,'wind']])for(let i=0;i<40;i++){cast(el,4+i/30,i%2===0);for(const r of fx[key].ribbons)for(const n of r.positions)assert(Number.isFinite(n));}});
test('Waves move through 3D space and retire after breaking',()=>{fx.reset();cast(3,6);const j=fx.jobs[0],z=j.root.position.z;fx.update(6.5);assert(j.root.position.z>z+3);fx.update(8);assert.equal(fx.jobs.length,0);assert(!j.root.visible);});
test('Earth columns emerge sequentially and launch tumbling debris',()=>{fx.reset();cast(4,9);fx.update(9.25);const j=fx.jobs[0];assert(j.columns[0].visible);assert(j.columns[0].position.y>j.columns[4].position.y);assert(fx.debris.mesh.count>0);assert(fx.debris.mesh.count<=160);});
test('Storm lightning segment counts remain inside the GPU buffers',()=>{fx.reset();cast(2,11,true);assert(fx.electric.meshes.every(m=>m.count>100&&m.count<=620));});
test('Conduction arcs originate at both animated hands in world space',()=>{fx.reset();const hands=[new THREE.Vector3(.3,1.8,2.8),new THREE.Vector3(1.7,1.7,2.9)],starts=[],original=fx.electricSegment;fx.handOrigins=hands;fx.electricSegment=function(a,b,index,radius){starts.push(new THREE.Vector3(...a));return original.call(this,a,b,index,radius);};cast(2,11.1);for(const hand of hands)assert(starts.some(start=>fx.electric.root.localToWorld(start.clone()).distanceTo(hand)<.0001));fx.electricSegment=original;fx.handOrigins=null;});
test('Held wave and earth casting reuse bounded geometry and material pools',()=>{fx.reset();for(let t=12;t<16;t+=1/30){cast(3,t);cast(4,t);}const geos=fx.geometries.length,mats=fx.materials.length;for(let t=16;t<22;t+=1/30){cast(3,t,true);cast(4,t,true);assert(fx.jobs.length<=10);}assert.equal(fx.geometries.length,geos);assert.equal(fx.materials.length,mats);});
test('Reset removes all live visual attacks',()=>{fx.reset();assert.equal(fx.jobs.length,0);assert(!fx.fire.root.visible&&!fx.wind.root.visible&&!fx.electric.root.visible);assert.equal(fx.debris.mesh.count,0);});
test('All seven tiers preserve finite vertices and lightning capacity',()=>{for(let tier=1;tier<=7;tier++)for(let el=0;el<5;el++){fx.reset();fx.cast({x:0,y:3,z:0,dx:.6,dz:.8,element:el,tier,ultimate:true},40+tier,27);fx.update(40+tier+.1);assert(fx.states[el].power<=1.8);if(el===2)assert(fx.electric.meshes.every(m=>m.count<=620));}});
test('Each tier adds rendered fire/air detail and increases actual water/earth geometry scale',()=>{let fire=0,air=0,water=0,earth=0;for(let tier=1;tier<=7;tier++){fx.reset();fx.cast({x:0,z:0,dx:0,dz:1,element:1,tier},90,27);fx.update(90.1);const flames=fx.fire.tongues.filter(m=>m.visible).length;assert(flames>fire);fire=flames;fx.cast({x:0,z:0,dx:0,dz:1,element:0,tier},90,27);fx.update(90.1);const gusts=fx.wind.ribbons.filter(r=>r.mesh.visible).length;assert(gusts>air);air=gusts;fx.cast({x:0,z:0,dx:0,dz:1,element:3,tier},90,27);fx.cast({x:0,z:0,dx:0,dz:1,element:4,tier},90,27);fx.update(90.2);const w=fx.jobs.find(j=>j.el===3).root.scale.y,e=fx.jobs.find(j=>j.el===4).root.scale.y;assert(w>water);assert(e>earth);water=w;earth=e;}});
console.log('\n'+passed+' effect lifecycle checks passed.');
