const {test}=require('node:test'),assert=require('node:assert/strict');
const {CampaignGame,CampaignState}=require('../campaign.js');
function arena(){const g=new CampaignGame(new CampaignState(),{demo:true});g.gates=[];g.orbs=[];g.encounters=[];g.obstacles=[];g.shrine.done=true;g.player.x=0;g.player.z=0;return g;}
function foe(g,x=0,z=15){const e=g.makeEnemy(x,z);e.weakness=-1;return e;}
test('Lightning paralyzes at Tier 1, cancels windups and leaves a recovery window',()=>{const g=arena(),e=foe(g);g.telegraph(e,'strike');g.hit(e,1,2);assert.equal(g.telegraphs.length,0);assert.ok(e.status.stun>=.7);const stop=e.status.stun;g.time=.4;g.hit(e,1,2);assert.equal(e.status.stun,stop);g.time=.8;const x=e.x,z=e.z;g.enemyStep(e,.1);assert.ok(e.x!==x||e.z!==z);g.time=2.1;g.hit(e,1,2);assert.ok(e.status.stun>g.time);});
test('Earth interrupts a pending attack and grants temporary forty percent protection',()=>{const g=arena(),e=foe(g);g.telegraph(e,'strike');g.hit(e,1,4);assert.equal(g.telegraphs.length,0);assert.ok(e.status.stun>g.time);g.damage(20);assert.equal(g.player.hp,88);g.shield=0;g.player.invincible=0;g.damage(20);assert.equal(g.player.hp,68);});
test('Boss paralysis builds stagger instead of disabling every cast; full stagger cancels attacks',()=>{const g=arena(),e=g.boss;e.active=true;g.telegraph(e,'ring');g.hit(e,1,2);assert.ok(e.stagger>=12);assert.ok(!(e.status.stun>g.time));assert.equal(g.telegraphs.length,1);e.stagger=99.99;g.hit(e,10,4);assert.ok(e.status.stun>g.time);assert.equal(g.telegraphs.length,0);});
test('Fire burns without refreshing itself, erupts on defeat and ignites nearby foes only',()=>{const g=arena(),e=foe(g),near=foe(g,2),far=foe(g,10),inactive=foe(g,1);inactive.active=false;g.hit(e,1,1);const expiry=e.status.burn;g.time=.1;const hp=e.hp;g.enemyStep(e,1/60);assert.ok(e.hp<hp);assert.equal(e.status.burn,expiry);g.hit(e,1000,0);assert.equal(g.events.filter(e=>e.type==='ignition').length,1);assert.ok(near.hp<near.max&&near.status.burn>g.time);assert.equal(far.hp,far.max);assert.equal(inactive.hp,inactive.max);});
test('Fire defeat chains consume each enemy once and cannot cross intervening cover',()=>{const g=arena(),a=foe(g,-2,15),b=foe(g,2,15),c=foe(g,-2,17);b.hp=10;c.hp=10;g.obstacles=[{x:0,z:16,w:.5,d:2}];g.hit(a,1000,1);assert.equal(b.hp,10);assert.equal(c.hp,0);assert.equal(g.events.filter(e=>e.type==='ignition').length,2);});
test('Water defeat healing is capped at full health and cannot repeat on a corpse',()=>{const g=arena(),e=foe(g);g.player.hp=95;g.hit(e,1000,3);assert.equal(g.player.hp,100);g.player.hp=70;g.hit(e,1000,3);assert.equal(g.player.hp,70);});
