const {test}=require('node:test'),assert=require('node:assert/strict');
const {KeyboardControls,movement}=require('../keyboard.js');
const {CampaignGame,CampaignState}=require('../campaign.js');
class Target {constructor(){this.listeners={};this.activeElement={tagName:'CANVAS'};this.hidden=false;}addEventListener(n,f){(this.listeners[n]??=[]).push(f);}removeEventListener(n,f){this.listeners[n]=this.listeners[n].filter(x=>x!==f);}emit(n,code,extra={}){const e={code,repeat:false,prevented:false,preventDefault(){this.prevented=true;},...extra};for(const f of this.listeners[n]||[])f(e);return e;}}
function setup(){const host=new Target(),doc=new Target(),actions=[];let playing=true,escapes=0,suspends=0;const k=new KeyboardControls({host,doc,isPlaying:()=>playing,onAction:c=>actions.push(c),onEscape:()=>{escapes++;playing=!playing;},onSuspend:()=>{suspends++;playing=false;}});return {host,doc,k,actions,setPlaying:v=>playing=v,get escapes(){return escapes;},get suspends(){return suspends;}};}
test('A quick attack tap survives keyup until one frame consumes it; pause clears it',()=>{const s=setup();s.host.emit('keydown','Space');s.host.emit('keyup','Space');assert(!s.k.keys.has('Space'));assert(s.k.takePress('Space'));assert(!s.k.takePress('Space'));s.host.emit('keydown','KeyC');s.k.reset();assert(!s.k.takePress('KeyC'));});
test('At 120 FPS, taps between simulation ticks still cast and cycle exactly once',()=>{const g=new CampaignGame(new CampaignState(),{demo:true});g.gates=[];g.orbs=[];g.encounters=[];g.obstacles=[];const a=g.makeEnemy(0,20),b=g.makeEnemy(3,22);g.targetId=a.id;g.advance(1/120,{cycle:true,cast:true});g.advance(1/120,{});assert.equal(g.events.filter(e=>e.type==='cast').length,1);assert.equal(g.targetId,b.id);for(let i=0;i<120;i++)g.advance(1/120,{});assert.equal(g.events.filter(e=>e.type==='cast').length,1);});
test('WASD and arrows follow screen directions through a complete camera orbit',()=>{const s=setup();for(const yaw of [0,Math.PI/2,Math.PI,Math.PI*1.5]){s.host.emit('keydown','KeyD');const a=s.k.axes(),r=movement(a.x,a.z,yaw);assert(Math.abs(r.mx+Math.cos(yaw))<1e-9);assert(Math.abs(r.mz-Math.sin(yaw))<1e-9);s.k.reset();s.host.emit('keydown','ArrowUp');const f=movement(s.k.axes().x,s.k.axes().z,yaw);assert(Math.abs(f.mx-Math.sin(yaw))<1e-9);assert(Math.abs(f.mz-Math.cos(yaw))<1e-9);s.k.reset();}s.host.emit('keydown','KeyA');s.host.emit('keydown','KeyD');assert.equal(s.k.axes().x,0);});
test('Holding move, cast, sword and tempest is independent; release clears only that key',()=>{const s=setup();for(const code of ['KeyW','Space','KeyC','KeyE'])assert(s.host.emit('keydown',code).prevented);assert.equal(s.k.keys.size,4);s.host.emit('keyup','Space');assert(!s.k.keys.has('Space'));assert(s.k.keys.has('KeyW')&&s.k.keys.has('KeyC')&&s.k.keys.has('KeyE'));});
test('Targeting, switching, mute and reset trigger once per press',()=>{const s=setup();for(const code of ['Tab','Digit1','Digit5','Numpad3','KeyM','KeyR']){s.host.emit('keydown',code);s.host.emit('keydown',code,{repeat:true});s.host.emit('keyup',code);}assert.equal(s.actions.length,6);});
test('Menu keys retain native button/tab behavior; Escape works from a settings field without repeat flicker',()=>{const s=setup();s.setPlaying(false);assert(!s.host.emit('keydown','Space').prevented);assert(!s.host.emit('keydown','Tab').prevented);assert.equal(s.k.keys.size,0);s.doc.activeElement={tagName:'SELECT'};s.host.emit('keydown','Escape');s.host.emit('keydown','Escape',{repeat:true});assert.equal(s.escapes,1);});
test('Text fields, composition and browser shortcuts never start attacks',()=>{const s=setup();for(const el of [{tagName:'INPUT'},{tagName:'TEXTAREA'},{tagName:'DIV',isContentEditable:true}]){s.doc.activeElement=el;s.host.emit('keydown','Space');assert.equal(s.k.keys.size,0);}s.doc.activeElement={tagName:'CANVAS'};s.host.emit('keydown','KeyW');s.host.emit('keydown','KeyC',{ctrlKey:true});assert.equal(s.k.keys.size,0);s.host.emit('keydown','KeyE',{isComposing:true});assert.equal(s.actions.filter(c=>c==='KeyC'||c==='KeyE').length,0);});
test('Focus loss and hidden tabs clear held input; stale repeats cannot restart an attack',()=>{const s=setup();s.host.emit('keydown','KeyW');s.host.emit('keydown','Space');s.host.emit('blur');assert.equal(s.k.keys.size,0);assert.equal(s.suspends,1);s.setPlaying(true);s.host.emit('keydown','Space',{repeat:true});assert.equal(s.k.keys.size,0);s.host.emit('keyup','Space');s.host.emit('keydown','Space');assert(s.k.keys.has('Space'));s.doc.hidden=true;s.doc.emit('visibilitychange');assert.equal(s.k.keys.size,0);assert.equal(s.suspends,2);});
test('Real keyboard state drives movement and unlimited combat at 30, 60 and 120 FPS',()=>{const results=[];for(const fps of [30,60,120]){const s=setup(),g=new CampaignGame(new CampaignState(),{demo:true,level:0,tier:1});g.player.invincible=999;g.orbs.forEach(o=>o.collected=true);s.host.emit('keydown','KeyW');s.host.emit('keydown','Space');for(let i=0;i<fps*3;i++){const a=s.k.axes();g.advance(1/fps,{...movement(a.x,a.z,0),cast:s.k.keys.has('Space')});}results.push({z:g.player.z,casts:g.events.filter(e=>e.type==='cast').length});s.host.emit('keyup','KeyW');s.host.emit('keyup','Space');const z=g.player.z,count=g.events.filter(e=>e.type==='cast').length;g.advance(.1,{...movement(s.k.axes().x,s.k.axes().z,0),cast:s.k.keys.has('Space')});assert.equal(g.player.z,z);assert.equal(g.events.filter(e=>e.type==='cast').length,count);}assert(results[0].casts>10);assert.deepEqual(results[0],results[1]);assert.deepEqual(results[1],results[2]);});

test('Shift remains unassigned',()=>{const s=setup();for(const c of ['ShiftLeft','ShiftRight'])assert(!s.host.emit('keydown',c).prevented);assert.equal(s.actions.length,0);assert.equal(s.k.keys.size,0);});
