const {test}=require('node:test'),assert=require('node:assert/strict'),Music=require('../music-director.js');
function setup(){const node=()=>({gain:{value:0,setTargetAtTime(v){this.value=v;}},connect(){},disconnect(){this.disconnected=true;}});const owner={musicVolume:.55,context:{currentTime:0,createGain:node,createMediaElementSource:node},musicBus:node()},media=[];const m=new Music(owner,path=>{const a={path,readyState:4,currentTime:0,paused:true,plays:0,loads:0,listeners:{},addEventListener(k,f){this.listeners[k]=f;},load(){this.loads++;},play(){this.plays++;this.paused=false;return Promise.resolve();},pause(){this.paused=true;},removeAttribute(){}};media.push(a);return a;});m.setWorld({exploration:'a.mp3',combat:'b.mp3'});return {m,media,owner};}
async function tick(m,seconds,active=true,combat=false){for(let i=0;i<Math.round(seconds*60);i++){m.update(1/60,active,combat);await Promise.resolve();assert([...m.decks,...(m.retiring?[m.retiring]:[])].filter(d=>d.value>.0001&&!d.disposed).length<=2);}}
test('Combat enters in 2.5 seconds, remains across gaps, returns after six seconds plus four',async()=>{const {m,media}=setup();await tick(m,.1);await tick(m,2.6,true,true);assert(m.angle>1.57);await tick(m,5.9);assert(m.angle>1.57);await tick(m,4.2);assert.equal(m.angle,0);assert(media[1].paused);});
test('Reentry reverses from current gains and resumes existing tracks without resetting time',async()=>{const {m,media}=setup();await tick(m,3,true,true);media[1].currentTime=27;await tick(m,7);const angle=m.angle;await tick(m,.1,true,true);assert(m.angle>angle);assert.equal(media[1].currentTime,27);assert.equal(media.length,2);});
test('Pause excludes elapsed time from clear timer and preserves playback positions',async()=>{const {m,media}=setup();await tick(m,3,true,true);await tick(m,2);const clear=m.clear;media[1].currentTime=31;await tick(m,20,false);assert.equal(m.clear,clear);assert(media.every(a=>a.paused));await tick(m,.1,true,true);assert.equal(media[1].currentTime,31);assert(!media[1].paused);});
test('Delayed destination keeps current cue audible, retries, then crossfades',async()=>{const {m,media}=setup();await tick(m,.1);media[1].readyState=0;await tick(m,7,true,true);assert.equal(m.angle,0);assert.equal(m.decks[0].value,1);assert(media[1].loads<=2);media[1].readyState=4;await tick(m,8,true,true);assert(m.angle>1.57);});
test('World changes and stale promises cannot revive disposed media; voices remain bounded',async()=>{const {m}=setup();await tick(m,.2);const first=m.decks[0];let resolve; m.decks[1].a.play=()=>new Promise(r=>resolve=r);m.update(.1,true,true);m.setWorld({exploration:'c.mp3',combat:'d.mp3'});resolve();await Promise.resolve();await tick(m,3);assert(first.disposed);for(let i=0;i<20;i++){m.setWorld({exploration:'c.mp3',combat:'d.mp3'});await tick(m,.1,true,i%2===0);}await tick(m,3);assert(!m.retiring);m.dispose();assert.equal(m.decks.length,0);});

test('Reloading the same world restarts exploration; a missing initial combat cue leaves exploration audible',async()=>{const {m,media}=setup();media[1].readyState=0;await tick(m,.2,true,true);assert.equal(m.decks[0].value,1);const pair=m.pair;m.decks[0].a.currentTime=99;m.setWorld(pair);assert.equal(m.decks[0].a.currentTime,0);await tick(m,3);assert(!m.retiring);});
