const {test}=require('node:test'),assert=require('node:assert/strict');
const {CampaignGame,CampaignState,damageScale,powerNames,tierFeatures}=require('../campaign.js');
global.THREE=require('../three.min.js');const {pose,SwordTrail}=require('../sword-motion.js');
function sandbox(tier=1){const g=new CampaignGame(new CampaignState(),{demo:true,tier});g.gates=[];g.orbs=[];g.encounters=[];g.obstacles=[];g.shrine.done=true;return g;}
test('Every element deals increasing real damage at each of seven tiers, with event metadata',()=>{for(let el=0;el<5;el++){let prior=0;for(let tier=1;tier<=7;tier++){const g=sandbox(tier),e=g.makeEnemy(0,20);g.element=el;e.weakness=-1;g.random=()=>1;g.cast(e);const dealt=e.max-e.hp;assert(Math.abs(dealt-8*damageScale[tier-1])<1e-8);assert(dealt>prior);prior=dealt;const event=g.events.find(e=>e.type==='cast');assert.equal(event.tier,tier);assert.equal(event.element,el);assert.equal(new Set(powerNames[el]).size,7);} }assert.equal(tierFeatures.length,7);});
test('Tier progress survives actual guardian completion, mission entry, checkpoint reload and death',()=>{let c=new CampaignState();c.unlocked=[0,1,2,3,4];for(let id=0;id<7;id++){let g=new CampaignGame(c,{level:id});assert.equal(g.tier,id+1);g.saveCheckpoint();c=CampaignState.parse(c.serialize());g=new CampaignGame(c);assert.equal(g.tier,id+1);g.player.hp=1;g.damage(1000);assert.equal(g.tier,id+1);assert.equal(g.unlocks.size,5);g.relays.forEach(r=>r.hp=0);g.boss.active=true;g.hit(g.boss,999999,1);assert(g.finished);assert(c.completed.includes(id));c=CampaignState.parse(c.serialize());}});
test('Impact specialization multiplies power on top of the campaign tier',()=>{const c=new CampaignState();c.completed=[0,1,2,3,4,5];c.highest=6;c.unlocked=[0,1,2,3,4];for(let n=0;n<3;n++)c.upgrade(2,'impact');const g=new CampaignGame(c,{level:6});g.obstacles=[];g.gates=[];g.element=2;const e=g.makeEnemy(g.player.x,g.player.z+12);e.weakness=-1;g.cast(e);assert(Math.abs(e.max-e.hp-8*3*1.45)<1e-8);});
test('Sword combo cycles crosscut, rising cut and heavier finisher; stopping resets it',()=>{const g=sandbox(),e=g.makeEnemy(0,10);e.hp=e.max=10000;g.enemyStep=()=>{};g.player.z=7;for(let i=0;i<72;i++)g.advance(1/60,{sword:true});const events=g.events.filter(e=>e.type==='sword');assert.deepEqual(events.slice(0,3).map(e=>e.combo),[1,2,3]);assert(g.events.filter(e=>e.type==='cast'&&e.sword).every(e=>e.tier===1&&e.combo>0));for(let i=0;i<100;i++)g.advance(1/60,{});g.cast(e,false,true);assert.equal(g.combo,1);assert(g.swordDuration>0);});
test('Three sword poses have different paths, finite joints and smooth return to guard',()=>{const ends=[];for(let combo=1;combo<=3;combo++){for(let i=0;i<=120;i++){const p=pose(combo,i/120);for(const value of Object.values(p).flat())if(typeof value==='number')assert(Number.isFinite(value));}ends.push(pose(combo,.62).tip);pose(combo,0).hand.forEach((v,i)=>assert(Math.abs(v-pose(combo,1).hand[i])<1e-10));assert(pose(combo,.4).trail);assert(!pose(combo,1).trail);}assert.notDeepEqual(ends[0],ends[1]);assert.notDeepEqual(ends[1],ends[2]);});
test('Blade trail follows world-space blade endpoints and remains bounded through repeated combos',()=>{const scene=new THREE.Scene(),trail=new SwordTrail(scene);for(let i=0;i<6000;i++){const t=i/120;trail.update(t,{base:new THREE.Vector3(Math.sin(t),1,t),tip:new THREE.Vector3(Math.cos(t),3,t+1)},true,i%5,Math.floor(i/40)%3+1,false);assert(trail.samples.length<=24);assert(trail.geometry.drawRange.count<=138);}for(const n of trail.positions)assert(Number.isFinite(n));const last=trail.samples.at(-1);assert.equal(trail.positions[(trail.samples.length-1)*6+2],Math.fround(last.base.z));trail.update(60,null,false,1,3,false);assert(!trail.mesh.visible);trail.reset();assert.equal(trail.samples.length,0);trail.dispose();assert.equal(scene.children.length,0);});
