const assert=require('node:assert/strict');
class El{constructor(action){this.dataset={touch:action};this.handlers={};this.style={};this.checked=false;this.classes=new Set();this.classList={add:c=>this.classes.add(c),remove:c=>this.classes.delete(c),toggle:(c,v)=>v?this.classes.add(c):this.classes.delete(c)};}addEventListener(n,f){(this.handlers[n]??=[]).push(f)}setPointerCapture(){}getBoundingClientRect(){return {left:0,top:0,width:122,height:122}}querySelectorAll(q){return q==='[data-touch]'?buttons:buttons.filter(b=>b.classes.has('pressed'))}emit(n,id,x=61,y=61,type='touch'){for(const f of this.handlers[n]||[])f({pointerId:id,clientX:x,clientY:y,pointerType:type,preventDefault(){}})}}
const buttons=['cast','tempest','dash','target','sword'].map(a=>new El(a)),root=new El(),stick=new El(),knob=new El(),game=new El(),checkbox=new El(),canvas=new El();global.window={};global.matchMedia=()=>({matches:true});Object.defineProperty(global,'navigator',{value:{maxTouchPoints:2},configurable:true});global.document={querySelector:s=>({'#touchControls':root,'#moveStick':stick,'#stickKnob':knob,'#game':game,'#touchEnabled':checkbox})[s]};require('../touch.js');let dash=0,cycle=0,look=0;const t=new window.TouchControls({canvas,onLook:()=>look++,onCycle:()=>cycle++,onDash:()=>dash++});let passed=0;function test(n,f){t.reset();f();console.log('PASS '+n);passed++;}
test('Movement and casting have separate pointer ownership',()=>{stick.emit('pointerdown',1,61,20);buttons[0].emit('pointerdown',2);assert(t.y>.9);assert(t.casting);buttons[0].emit('pointerup',2);assert(!t.casting);assert(t.y>.9);stick.emit('pointerup',1);assert.equal(t.y,0);});
test('Two fingers can cast and use tempest at the same time',()=>{buttons[0].emit('pointerdown',2);buttons[1].emit('pointerdown',3);assert(t.casting&&t.tempest);buttons[1].emit('pointercancel',3);assert(t.casting&&!t.tempest);});
test('A third finger can look without canceling movement or casting',()=>{stick.emit('pointerdown',1,20,61);buttons[0].emit('pointerdown',2);canvas.emit('pointerdown',3,100,100);canvas.emit('pointermove',3,120,130);assert(look>0&&t.x<-.9&&t.casting);canvas.emit('pointerup',3);assert(t.casting);});
test('Canceled joystick and lost action capture release only their own input',()=>{stick.emit('pointerdown',1,20,61);buttons[0].emit('pointerdown',2);stick.emit('pointercancel',1);assert.equal(t.x,0);assert(t.casting);buttons[0].emit('lostpointercapture',2);assert(!t.casting);});
test('Dash and target switch trigger once at contact',()=>{buttons[2].emit('pointerdown',1);buttons[3].emit('pointerdown',2);assert.equal(dash,1);assert.equal(cycle,1);});
test('Pause/reset and disabling touch clear all held controls',()=>{stick.emit('pointerdown',1,20,61);buttons[0].emit('pointerdown',2);t.reset();assert(!t.casting&&t.x===0&&t.lookId===null);t.setEnabled(false);buttons[0].emit('pointerdown',7);assert(!t.casting);t.setEnabled(true);assert(checkbox.checked);});
test('Sword touch input does not interrupt held movement',()=>{stick.emit('pointerdown',1,61,20);buttons[4].emit('pointerdown',2);assert(t.y>.9&&t.sword);buttons[4].emit('pointerup',2);assert(t.y>.9&&!t.sword);});
console.log(passed+' multitouch checks passed');
